import random

leap1=[("I totally agree with this opinion.","私たちはこの意見に全面的に賛成です。[No.1]"),
("strongly oppose the plan","その計画に強固に反対する。[No.2]"),
("advise him not to eat too much","食べ過ぎないよう彼に忠告する。[No.3]"),
("tips on how to use the library","図書館の利用法に関するヒント。[No.4]"),
("discuss the problem with a specialist","専門家とその問題について話し合う。[No.5]"),
("blame the car's brakes for the accident","その事故の原因は車のブレーキにあるとする。[No.6]"),
("argue that reading aloud is important","音読は大切だと主張する。[No.7]"),
("claim that a vegetarian diet is better than meat diet","菜食は肉食より優れていると主張する。[No.8]"),
("complain about their loud music","彼らのうるさい音楽に文句を言う。[No.9]"),
("offer him some coffee","彼にコーヒーはどうですかと尋ねる(申し出る)。[No.10]"),
("That letter suggests that she is quite happy in her job.","その手紙は彼女が仕事をかなり楽しんでいることを示唆している。[No.11]"),
("What would you recommend?","＜レストランなどで＞何がお勧めですか(何を勧めますか).[No.12]"),
("I am grateful for your help.","ご助力に感謝しています。[No.13]"),
("apologize to her for being late","遅刻したことを彼女に謝る。[No.14]"),
("Don't make excuses.","言い訳をするな。[No.15]"),
("celebrate her 18th birthday","彼女の18歳の誕生日を祝う。[No.16]"),
("congratulate her on her exam results","試験結果について彼女を祝福する。[No.17]"),
("admire him for his great performance","すばらしい演技に対して彼を称賛する。[No.18]"),
("I was deeply impressed by his speech.","彼の演説に深い感銘を受けた(感銘を与えられた)。[No.19]"),
("an award ceremony","授賞式。[No.20]"),
("explain the rules of baseball to him","彼に野球のルールを説明する。[No.21]"),
("Could you describe your lost bag?","なくしたバッグ(の特徴)を説明していただけませんか。[No.22]"),
("communicate with each other in sign language","手話でお互いに意思の疎通をはかる。[No.23]"),
("express your opinions clearly.","はっきりと意見を言い(を表現し)なさい。[No.24]"),
("make a promise to lose weight","減量するという約束をする。[No.25]"),
("various kinds of information","さまざまな情報。[No.26]"),
("science and technology","科学技術(科学と技術)。[No.27]"),
("do research on space rockets","宇宙ロケットに関する研究を行う。[No.28]"),
("collect materials for a paper.","レポートの材料を集める。[No.29]"),
("artificial intelligence.","人工知能。[No.30]"),
("an electric car.","電気自動車。[No.31]"),
("invent a speaking robot.","会話のできるロボットを発明する。[No.32]"),
("discover a human mummy.","人間のミイラを発見する。[No.33]"),
("develop into a big city.","大都市に発展する。[No.34]"),
("improve my tennis skills.","テニスの技術を高める。[No.35]"),
("improve my ability to speak English.","英語を話す力を伸ばす。[No.36]"),
("how my musical talent.","音楽の才能を発揮する。[No.37]"),
("make an effort to be on time.","時間に間に合うように努力する。[No.38]"),
("We have practice on Saturday.","土曜日に練習がある。[No.39]"),
("a soccer game between Japan and Brazil.","日本とブラジルのサッカーの試合。[No.40]"),
("achieve his goal of becoming a vet.","獣医になるという目標を達成する。[No.41]"),
("I managed to catch the last train.","何とか終電に乗ることができた。[No.42]"),
("improve my cooking skills.","私の料理の腕を上達させる 。[No.43]"),
("produce rice and vegetables.","米と野菜を生産する。[No.44]"),
("create a website.","ホームページを創る。[No.45]"),
("establish a close friendship with him.","彼と親密な友情を築く。[No.46]"),
("This will save you a lot of trouble.","これによって多くの手間が省ける。[No.47]"),
("take the medicine twice a day.","１日に２回その薬を飲む。[No.48]"),
("The patient is getting better.","その患者は快方に向かっている。[No.49]"),
("My body is in good condition.","私の体は調子がよい。[No.50]"),
("medical expenses.","医療費 。[No.51]"),
("have a lot of stress.","ストレスが多い。[No.52]"),
("I am sufferam ing from jet lag.","時差ぼけに苦しんでいる。[No.53]"),
("get light exercise.","軽い運動をする。[No.54]"),
("breathe deeply.","深呼吸する。[No.55]"),
("I'm really thirsty.","本当にのどが渇いた。[No.56]"),
("physical health.","体の健康。[No.57]"),
("I have a fever.","熱がある。[No.58]"),
("build up my physical strength.","体力をつける。[No.59]"),
("was moved to tears.","私は感動して泣いた。[No.60]"),
("This apple tastes sweet.","このリンゴは甘い(味がする)。[No.61]"),
("It is against the rules.","それは規則違反だ。[No.62]"),
("play an important role in society.","社会で重要な役割を果たす。[No.63]"),
("have a habit of making excuses.","言い訳をする癖がある。[No.64]"),
("Different countries have different customs.","習慣は国よっても違う(異なる国は異なる習慣をもつ)。[No.65]"),
("Japanese traditions.","日本の伝統。[No.66]"),
("women's status in society.","社会での女性の地位。[No.67]"),
("Parking here is against the law.","ここでの駐車は法律違反だ。[No.68]"),
("My ancestors were French.","私の祖先はフランス人だった。[No.69]"),
("The population of Tokyo is larger than that of Osaka.","東京の人口は大阪の人口より多い。[No.70]"),
("his native language.","彼の母(国)語。[No.71]"),
("find a job abroad.","海外で仕事を見つける。[No.72]"),
("a local bank.","地元の銀行。[No.73]"),
("according to a recent survey.","最近の調査によると。[No.74]"),
("he value of the painting.","その絵の価値。[No.75]"),
("a national treasure.","国宝。[No.76]"),
("follow the latest fashion.","最新の流行を追う。[No.77]"),
("the general public.","一般大衆。[No.78]"),
("a body of strong evidence.","一連の有力な証拠。[No.79]"),
("receive the 45% of the vote.","投票数の45%を獲得する。[No.80]"),
("the Japanese government.","日本政府。[No.81]"),
("the most powerful nation in the world.","世界で一番力のある国。[No.82]"),
("What is the capital of Canada?.","カナダの首都はどこですか。[No.83]"),
("the United states of America.","アメリカ合衆国 。[No.84]"),
("the political situation in Russia.","ロシアの政治情勢。[No.85]"),
("pay a very high price for the painting.","その絵に高額(の価格)を支払う。[No.86]"),
("Pay a large sum for antiques","骨董品に大金を使う[No.87]"),
("Our budget for this trip","今回の旅の予算[No.88]"),
("Pay a cancellation fee","キャンセル料を払う[No.89]"),
("Taxi fares are low in Singapore.","シンガポールのタクシー料金(運賃)は安い[No.90]"),
("May we have the bill?","お会計お願いします[No.91]"),
("Japan's trade with the U.S.","日本の対米貿易[No.92]"),
("Achieve wealth and power","富と権力を手にする[No.93]"),
("Boost the Japanese economy","日本経済を強化する[No.94]"),
("The suit cost me 500 dollars.","そのスーツは500ドルした(かかった)。[No.95]"),
("work for a big company.","大きな会社で働く。[No.96]"),
("accomplish a difficult task.","困難な仕事を成し遂げる。[No.97]"),
("earn money to pay my school fees.","学費を払う金を稼ぐ。[No.98]"),
("My back hurts a lot.","腰がとても痛い。[No.99]"),
("injure my back.","腰を痛める。[No.100]"),
("seriously damage the environment.","環境に深刻な被害を与える。[No.101]"),
("destroy all weapons.","すべての武器を破壊する。[No.102]"),
("You ruined my plan.","君のせいで計画が台無しだよ。[No.103]"),
("Tigers are in danger of extinction.","トラが絶滅の危機にある。[No.104]"),
("chat with a neighbor.","近所の人と話す。[No.105]"),
("draw a large audience.","大観衆を集める。[No.106]"),
("A crowd rushed into the hall.","群衆が会場になだれ込んだ。[No.107]"),
("the author of War and Peace.","『戦争と平和』の著者。[No.108]"),
("Most of the staff is from Australia.","職員の大半はオーストラリア出身です。[No.109]"),
("the clerks at that department store.","あのデパートの店員。[No.110]"),
("The restaurant was crowded with customers from abroad.","そのレストランは外国人客で混雑していた。[No.111]"),
("There were a lot of passengers on the train.","列車には多くの乗客が載っていた。[No.112]"),
("give up my seat to elderly people.","お年寄り(年配の人)に席を譲る。[No.113]"),
("female workers.","女性の労働者。[No.114]"),
("head for the beach.","海辺へ向かう。[No.115]"),
("Someone was following me.","誰かが私をつけていた。[No.116]"),
("wander around the town.","街をぶらぶら歩き回る。[No.117]"),
("travel around the world.","世界中を旅する。[No.118]"),
("pass the post office.","郵便局(の前)を通り過ぎる。[No.119]"),
("Things are likely to improve.","事態はよくなりそうだ。[No.120]"),
("It is only natural that you cannot catch words you do not know.","知らない単語を聞き取れないのはごく当然のことだ。[No.121]"),
("He is certain to become a star player.","彼はきっとスター選手になるよ。[No.122]"),
("The repairs will probably take a month.","修理はおそらく1か月はかかるだろう。[No.123]"),
("We are faced with a crisis.","私たちは危機に直面している。[No.124]"),
("avoid making eye contact with monkeys.","サルとは目を合わせないようにしなさい（サルと目を合わせることを避けろ）。[No.125]"),
("solve the math problem.","その数学の問題を解く。[No.126]"),
("have trouble sleeping.","寝付けない(眠るのに苦労する)。[No.127]"),
("an international issue.","国際問題。[No.128]"),
("cheer all the players on.","すべての選手たちに声援を送る。[No.129]"),
("encourage people to bike to work.","人々に自転車通勤するよう促す。[No.130]"),
("firmly support her.","強く彼女を支持する。[No.131]"),
("The heavy snow prevented us from going out.","大雪のため外出できなかった。[No.132]"),
("deny that he is a great scientist.","彼が偉大な科学者であることを否定する。[No.133]"),
("The Internet has enabled us to receive information right away.","インターネットのおかげで情報をすぐに得られるようになった。[No.134]"),
("succeed in landing on the moon.","月面着陸に成功する。[No.135]"),
("miss the last train.","終電を逃す。[No.136]"),
("fail in business.","商売で失敗する。[No.137]"),
("make grammatical mistakes.","文法ミスをする。[No.138]"),
("check the brakes.","そのブレーキを調べる。[No.139]"),
("hide the comic under the pillow.","枕の下に漫画を隠す。[No.140]"),
("draw her portrait.","彼女の似顔絵を描く。[No.141]"),
("join the baseball team.","野球部に入る。[No.142]"),
("throw me a rope.","ロープを投げてくれ。[No.143]"),
("operate five machines at once.","１度に5台の機械を操作する。[No.144]"),
("repair a bicycle.","自転車を修理する。[No.145]"),
("She sews all her own dresses.","彼女は自分の服を自分で縫っている。[No.146]"),
("raise your hand.","手を上げて。[No.147]"),
("serve wine to the guests.","客にワインを出す。[No.148]"),
("pour tea for all of the guests.","客みんなにお茶を注ぐ。[No.149]"),
("spill coffee all over my laptop.","コーヒーをノートパソコンの上にこぼす。[No.150]"),
("pretend to be sleeping.","寝ているふりをする。[No.151]"),
("He behaves badly in class.","彼の授業中の態度は悪い（彼は授業中、行儀悪くふるまう）。[No.152]"),
("cannot bear the noise.","騒音に耐えられない。[No.153]"),
("explore the surface of Mars.","火星の地表を探査する。[No.154]"),
("What happened to her?","彼女に何が起こったの。[No.155]"),
("The singer appeared on the stage.","その歌手がステージに現れた。[No.156]"),
("The cause of the accident remains unknown.","その事故の原因はいまだ知られていない。[No.157]"),
("eat grass in order to survive.","生き延びるため草を食べる。[No.158]"),
("Sam belongs to the Sales Department.","サムは営業部に所属している。[No.159]"),
("represent Japan at the World Cup.","ワールドカップ日本代表となる。[No.160]"),
("This novel is based on facts.","この小説は事実に基づいている。[No.161]"),
("The price includes postage.","価格には送料が含まれています。[No.162]"),
("his soup contains various herbs.","このスープにはさまざまな薬草が入っている。[No.163]"),
("with my own eyes.","私自身の目で。[No.164]"),
("share a table with a stranger.","知らない人と相席(席を共有)する。[No.165]"),
("collect teddy bears.","クマのぬいぐるみを集める。[No.166]"),
("gather information.","情報を集める。[No.167]"),
("the best soccer player in the history.","史上最高のサッカー選手。[No.168]"),
("a required subject.","必須科目。[No.169]"),
("receive a good education.","よい教育を受ける。[No.170]"),
("have a wide range of knowledge of cinema.","映画に関する幅広い知識を持っている。[No.171]"),
("wear a school uniform.","学校の制服を着ている。[No.172]"),
("She is in the eighth grade.","彼女は８年生(中学２年生)だ。[No.173]"),
("a college senior.","大学４年生。[No.174]"),
("graduate from high school.","高校を卒業する。[No.175]"),
("decide to live on my own.","一人で暮らすことを決心する。[No.176]"),
("judge someone by their appearance.","人を外見で判断する。[No.177]"),
("quit my job.","仕事をやめる。[No.178]"),
("retire from the company.","会社を(定年で)退職する。[No.179]"),
("a review of the tax system.","税制の見直し。[No.180]"),
("choose what to wear to school.","学校へ着ていく服を選ぶ。[No.181]"),
("imagine life without electricity.","電気のない生活を想像してごらん。[No.182]"),
("guess what is in this bag.","この袋に何が入っているかを当ててごらん。[No.183]"),
("We are expecting a typhoon.","台風が来るらしい。[No.184]"),
("predict when cherry blossoms will start to flower.","桜の開花時期を予測する。[No.185]"),
("I remember meeting her here.","彼女にここで会ったことを覚えています。[No.186]"),
("This song reminds me of him.","この歌は彼のことを私に思い出させる。[No.187]"),
("Jim realized that he did not love her any more.","ジムはもう彼女のことを愛していないことに気付いた。[No.188]"),
("appreciate the importance of discussion.","話し合いの重要性を理解する。[No.189]"),
("accept other people's opinions.","他人の意見を受け入れる。[No.190]"),
("consider all the possibilities.","すべての可能性を考える。[No.191]"),
("Do you mind if I open the window?","窓を開けてもいいですか(窓を開けるのを気にしますか)。[No.192]"),
("I wonder where he has gone.","彼はどこに行ってしまったのだろうか。[No.193]"),
("It seems that he knows what happened.","彼は起きたことを知っているようだ。[No.194]"),
("compare city life with country life.","都会の生活を田舎の生活と比較する。[No.195]"),
("concentrate on my studies.","勉強に集中する。[No.196]"),
("his book focuses on French culture.","この本はフランス文化に焦点を当てている。[No.197]"),
("Please allow me to introduce myself.","自己紹介をさせてください。[No.198]"),
("Tom admitted that he had been mistaken.","トムは自分が間違っていたことを認めた。[No.199]"),
("deep in the ground.","地中深くに。[No.200]"),
("prevent marine pollution.","海洋汚染を食い止める。[No.201]"),
("Snow is a rare sight in this area.","雪はこの地域では珍しい光景です。[No.202]"),
("enjoy a night view of Kobe.","神戸の夜景（夜の景色）を楽しむ。[No.203]"),
("the beautiful landscape of Scotland.","スコットランドの美しい風景。[No.204]"),
("prevent nature.","自然を守る。[No.205]"),
("sunflower seeds.","ひまわりの種。[No.206]"),
("water a plant.","植物に水をやる。[No.207]"),
("Flowers bloomed all over the field.","野原には一面花が咲いていた。[No.208]"),
("the rice harvest this year.","今年の米の収穫。[No.209]"),
("the chirping of insects.","虫の音。[No.210]"),
("There was an earthquake last week.","先週、地震が起きた。[No.211]"),
("The temperature reached 40 degrees.","気温が40度まで上がった。[No.212]"),
("freeze at zero degrees.","ゼロ度で凍る。[No.213]"),
("The flood washed the bridge away.","洪水で橋が流された。[No.214]"),
("The pond froze over.","池が一面凍った。[No.215]"),
("reflect the sunlight.","日光を反射する。[No.216]"),
("a polite young man.","礼儀正しい若い男性。[No.217]"),
("It is rude to ask women their age.","女性に年齢を尋ねるのは無礼です。[No.218]"),
("lonely old people.","孤独な老人たち。[No.219]"),
("He is lazy at work.","彼は仕事をいい加減にやる。[No.220]"),
("a strict rule.","厳しい規則。[No.221]"),
("The Ugly Duckling.","『醜いアヒルの子』。[No.222]"),
("a highly intelligent woman.","きわめて聡明な女性。[No.223]"),
("Don't be silly!","ばかなことを言う（する）な！[No.224]"),
("get nervous during the exam.","試験中にあがる。[No.225]"),
("The noise kept me awake all night.","騒音で一晩中眠れなかった。[No.226]"),
("She lives alone.","彼女は一人暮らしだ。[No.227]"),
("have a positive attitude toward life.","人生に対して前向きな姿勢でいる。[No.228]"),
("Printed books have character.","活字の本には味（特徴）がある。[No.229]"),
("one of the characteristics of large cities.","大都会の特徴の１つ。[No.230]"),
("Low rainfall is a feature of deserts.","少ない降水量は砂漠の特徴の１つだ。[No.231]"),
("check the details of the report.","その報告書の詳細を確認する。[No.232]"),
("There are advantages and disadvantages to self-driving cars.","自動運転の車にはメリットとデメリットがある。[No.233]"),
("complain about my husband's faults.","夫の欠点について文句を言う。[No.234]"),
("improve the quality of life.","生活の質を向上させる。[No.235]"),
("Let's see if our answers are correct.","答えが正しいかどうかみてみよう。[No.236]"),
("an ideal place for camping.","キャンプにはうってつけの場所。[No.237]"),
("It's not fair!","それは不公平だ。[No.238]"),
("clothes appropriate for a job interview.","仕事の面接に適切な服。[No.239]"),
("Kyoto is famous for its temples.","京都は寺で有名だ。[No.240]"),
("when I was in elementary school.","小学生のとき。[No.241]"),
("a major cause of global warming.","地球温暖化の主な原因。[No.242]"),
("It does not matter whether he succeeds or not.","彼が成功するかどうかは重要ではない。[No.243]"),
("The moon is bright tonight.","今夜は月が明るい。[No.244]"),
("swim in the brilliant sunshine.","まばゆい太陽光の下で泳ぐ。[No.245]"),
("have a lively conversation.","生き生きとした会話をする。[No.246]"),
("a comfortable bed.","快適なベッド。[No.247]"),
("I find it pleasant to talk with her.","彼女と話すのは楽しいと感じる。[No.248]"),
("Call me when it is convenient for you.","都合のよいときに電話してください。[No.249]"),
("false information.","誤った情報。[No.250]"),
("I have a terrible sense of direction.","私は方向音痴だ。[No.251]"),
("an awful smell of cat urine.","ネコの尿のひどい臭い。[No.252]"),
("a thin jacket.","薄い上着。[No.253]"),
("tight jeans.","きついジーンズ。[No.254]"),
("wear loose clothes.","ダボっとした服を着ている。[No.255]"),
("raw fish.","生魚。[No.256]"),
("an empty bottle.","空瓶。[No.257]"),
("This soap makes your skin very smooth.","この石けんでお肌はツルツルになります。[No.258]"),
("a direct flight to Paris.","パリへの直行便。[No.259]"),
("Shakespeare is familiar to people all over the world.","シェイクスピアは世界中の人々に知られている。[No.260]"),
("She is similar to her mother in appearance.","彼女は見た目が母親に似ている。[No.261]"),
("His tastes differ from mine.","彼の趣味は私の趣味と異なる。[No.262]"),
("The way people greet each other varies from country to country.","挨拶の仕方は国によりさまざまだ。[No.263]"),
("a specific age group.","ある特定の年齢のグループ。[No.264]"),
("E-books are becoming common.","電子書籍は普及しつつある。[No.265]"),
("These days, it is not unusual for men to wear makeup.","最近は、男性が化粧するのは珍しくない。[No.266]"),
("add some milk to the coffee.","コーヒーにミルクを加える。[No.267]"),
("increase by 30 percent.","30％増える。[No.268]"),
("reduce the amount of garbage.","生ゴミ（の量）を減らす。[No.269]"),
("divide the stew into small portions.","シチューを小分けにする。[No.270]"),
("count the money.","お金を数える。[No.271]"),
("weigh 40 kilograms.","40キロの重さだ。[No.272]"),
("a quarter to ten.","10時15分前（9:45）。[No.273]"),
("a lot of dolphins.","多くのイルカ。[No.274]"),
("a pile of ironed shirts.","アイロンをかけたシャツの山。[No.275]"),
("the declining birth rate.","少子化（下がりつつある出生率）。[No.276]"),
("memorize a list of figures.","数字の一覧を暗記する。[No.277]"),
("I am tired due to (a) lack of sleep.","私は睡眠不足のため疲れている。[No.278]"),
("an extra charge.","追加料金。[No.279]"),
("I'm not ready yet.","まだ準備ができていません。[No.280]"),
("prepare a meal.","食事の準備をする。[No.281]"),
("adjust to a new school life.","新しい学校生活に慣れる。[No.282]"),
("That rule applies to students.","その規則は学生に適用される。[No.283]"),
("What time suits you best?","何時が（あなたに）ご都合がいいですか。[No.284]"),
("In some cases, honesty does not pay.","正直が割に合わない場合もある。[No.285]"),
("a love scene.","ラブシーン。[No.286]"),
("a chance to play the lead.","主役を演じる機会。[No.287]"),
("have a golden opportunity to speak English.","英語を話す機会を持つ。[No.288]"),
("learn from experience.","経験から学ぶ。[No.289]"),
("If you have time, help me.","時間があれば手伝ってよ。[No.290]"),
("spring has come.","春が来た。[No.291]"),
("The station is ten minutes' walk from here.","駅はここから歩いて10分です。[No.292]"),
("a man past middle age.","中年過ぎの男性。[No.293]"),
("a generation gap.","世代間格差。[No.294]"),
("celebrate our school's 100th anniversary.","我が校の創立100周年を祝う。[No.295]"),
("I moved to this city just recently.","最近この市に引っ越してきました。[No.296]"),
("I used to drive to work, but nowadays I take the train.","以前は車で仕事に行っていたが、今は電車を利用する。[No.297]"),
("early in the morning.","朝早くに。[No.298]"),
("win first prize.","1等賞をとる。[No.299]"),
("follow the latest fashions.","最新のファッションを追う。[No.300]"),
("in modern society.","現代社会では。[No.301]"),
("in ancient times.","大昔に。[No.302]"),
("spend most of my time reading[in my room, with my family].","時間の大半を読書に[部屋の中で、家族と一緒に]費やす[過ごす]。[No.303]"),
("Our train was delayed (for) two hours.","私たちが乗った列車が2時間遅れた。[No.304]"),
("borrow two books from the library.","図書館から2冊の本を借りる。[No.305]"),
("Could you lend me 10,000 yen?","1万円貸してもらえませんか。[No.306]"),
("rent a car for six hours.","6時間、車を借りる。[No.307]"),
("provide students with an opportunity to study in the U.K.","イギリス留学の機会を学生に与える。[No.308]"),
("drill a hole through a board.","板にドリルで穴を開ける。[No.309]"),
("plastic garbage bags.","ビニールのごみ袋。[No.310]"),
("buy items on sale.","バーゲン品を買う。[No.311]"),
("the front wheel of my bicycle.","自転車の前輪。[No.312]"),
("take notes in class.","授業中にメモをとる。[No.313]"),
("open the present.","プレゼントを開ける。[No.314]"),
("find a good bargain.","お買い得品を見つける。[No.315]"),
("lift heavy stuff.","重い物を持ち上げる。[No.316]"),
("tie up the box with string.","ひもで箱を縛る。[No.317]"),
("enjoy my leisure (time).","余暇を楽しむ。[No.318]"),
("a well-balanced diet.","栄養バランスのとれた食事。[No.319]"),
("a set of furniture.","家具一式。[No.320]"),
("put the leftovers in the refrigerator.","冷蔵庫に残り物を入れる。[No.321]"),
("There is little traffic on the street today.","今日は通りに車が少ない。[No.322]"),
("We sold our car for 500,000 yen.","私たちは車を50万円で売った。[No.323]"),
("pay five dollars for the book.","その本の代金として5ドルを払う。[No.324]"),
("I wear contact lenses.","コンタクトレンズをつけている。[No.325]"),
("change my clothes.","服を着替える。[No.326]"),
("Will you marry me?","（私と）結婚してくれますか？[No.327]"),
("greet each other.","お互いに挨拶をする。[No.328]"),
("order rice directly from the farm.","産地に直接米を注文する。[No.329]"),
("book a single room for two nights.","シングルルームを2泊予約する。[No.330]"),
("a two-hundred-story skyscraper.","200階建ての超高層ビル。[No.331]"),
("a dam site.","ダムの用地。[No.332]"),
("mow the lawn in our yard.","私たちの庭の芝を刈る。[No.333]"),
("the bottom of the sea.","海底。[No.334]"),
("stand in line.","列に並ぶ。[No.335]"),
("the people sitting in the back row.","後列に座っている人。[No.336]"),
("Classical music was playing in the background.","BGMにクラシック音楽が流れていた。[No.337]"),
("go in the opposite direction.","反対の方向へ行く。[No.338]"),
("various foreign cultures.","さまざまな外国文化。[No.339]"),
("works of modern art.","現代芸術の作品。[No.340]"),
("Japanese animated cartoons.","日本のアニメーション作品。[No.341]"),
("the plot of this novel.","この小説のあらすじ。[No.342]"),
("play a musical instrument.","楽器を演奏する。[No.343]"),
("That is a nice tune.","いい曲だね。[No.344]"),
("delete the sentence.","その１文を削除する。[No.345]"),
("a magazine article on Portugal.","ポルトガルに関する雑誌の記事。[No.346]"),
("a famous passage from the Bible.","聖書の有名な一節。[No.347]"),
("increase my vocabulary.","語彙を増やす。[No.348]"),
("rumors about him spread throughout the school.","彼のうわさは学校中に広まった。[No.349]"),
("How do you spell your name?","名前はどのようにつづりますか。[No.350]"),
("How do you pronounce your name?","あなたの名前はどう発音するのですか。[No.351]"),
("show signs of recovery.","回復の兆しが見られる。[No.352]"),
("What does that mean?","それはどういう意味ですか。[No.353]"),
("This magazine is published twice a year.","この雑誌は年に２回発行されている。[No.354]"),
("display the latest fashions.","最新のファッションを展示する。[No.355]"),
("You can trust him; he keeps secrets.","彼のことを信頼してよい。彼は秘密を守る。[No.356]"),
("Your success depends on how much effort you make.","成功は君の努力次第だ。[No.357]"),
("You can rely on him.","彼なら頼っても大丈夫。[No.358]"),
("pray for her safety.","彼女の無事を祈る。[No.359]"),
("beg her to overlook my mistakes.","ミスを見逃してもらうよう彼女にお願いする。[No.360]"),
("prefer beef to chicken.","鶏肉より牛肉を好む。[No.361]"),
("All America wept.","全米が泣いた。[No.362]"),
("hate doing housework.","家事をするのが嫌いだ。[No.363]"),
("Don't worry about it.","そんなことを気にするな。[No.364]"),
("I'm anxious about her health.","彼女の健康が心配だ。[No.365]"),
("I'm not satisfied with the exam result.","試験結果に満足していない。[No.366]"),
("It really annoys me when I see people smoking while (they are) walking.","歩きタバコを見ると頭にくる。[No.367]"),
("I'm sorry to bother you, but could you give me a hand?","ご迷惑をおかけしてすみませんが、手を貸していただけないでしょうか。[No.368]"),
("Don't disturb other people.","ほかの人に迷惑をかけないようにしなさい+K330:L373。[No.369]"),
("I am frightened of spiders.","クモが怖い（クモにおびえさせられる）。[No.370]"),
("I regret that I did not study hard in my teens.","10代のころ一生懸命に勉強しなかったことを後悔している。[No.371]"),
("Could you do me a couple of favors?","いくつかお願いがあるのですが。[No.372]"),
("have an interest in history.","歴史に興味を持っている。[No.373]"),
("It is a pity that you missed the movie.","あなたがその映画を見損ねたのは残念です。[No.374]"),
("Our flight was delayed due to the storm.","嵐のために飛行機が遅れた。[No.375]"),
("agree with his opinion for the following reasons.","次の理由で彼の意見に賛成だ。[No.376]"),
("as a result of inflation.","インフレの結果として。[No.377]"),
("Drinking too much has a bad effect on the brain.","過度の飲酒は脳に悪影響を与える。[No.378]"),
("have a strong influence on them.","彼らに強い影響を与える。[No.379]"),
("We ended up spending the night at that airport.","私たちは結局、空港で一夜を過ごすことになった。[No.380]"),
("cause trouble.","面倒を引き起こす。[No.381]"),
("Lack of sleep seriously affects your performance at work.","睡眠不足は仕事に悪影響を及ぼす。[No.382]"),
("my way of studying.","私の勉強の仕方。[No.383]"),
("behave in a responsible manner.","責任ある方法でふるまう。[No.384]"),
("What is the purpose of your visit?","あなたの訪問の目的は何ですか。[No.385]"),
("for the sake of your health.","健康のため。[No.386]"),
("right in front of me.","私のちょうど目の前で。[No.387]"),
("a complete stranger.","見ず知らずの人。[No.388]"),
("I can hardly wait for the summer.","夏が待ち遠しい。[No.389]"),
("I go to the gym almost every day.","ほとんど毎日ジムに通っている。[No.390]"),
("I am partly to blame.","私にも一部責任がある。[No.391]"),
("Jim looks happy, but actually he's sad.","ジムは幸せそうだけど本当は悲しい。[No.392]"),
("He is indeed a kind person.","彼は本当に親切な人です。[No.393]"),
("even Homer sometimes nods.","《ことわざ》弘法にも筆の誤り。[No.394]"),
("Where exactly did you stay in Australia?","オーストラリアの正確にはどこに滞在したのですか。[No.395]"),
("Land prices are gradually increasing.","土地の値段が徐々に上がっている。[No.396]"),
("Even experts are only human, and therefore mistakes sometimes occur.","専門家でもただの人間だ．それゆえ，ミスが時々起こる。[No.397]"),
("If you can't make it, your mother may go instead.","もしあなたが行けないのなら、君のお母さんが代わりに行ってもよい。[No.398]"),
("We are open until 11 p.m. on weekends.","平日は午後11時まで営業しています。[No.399]"),
("learn another foreign language besides English.","英語以外の外国語を勉強する。[No.400]"),
("Everybody was asleep except (for) him.","彼以外は皆眠っていた。[No.401]"),
("the debate on whaling.","捕鯨に関する討論。[No.402]"),
("Stop criticizing my cooking!","私の料理を批判するのをやめて。[No.403]"),
("accuse her of lying.","嘘をついたことで彼女を非難する。[No.404]"),
("insist on returning home.","家に帰ると言い張る。[No.405]"),
("object to my studying abroad.","私の留学に反対する。[No.406]"),
("protest against nuclear tests.","核実験に抗議する。[No.407]"),
("highly controversial issue.","非常に論争になっている問題。[No.408]"),
("He is bound to be in the classroom.","今彼はきっと教室にいるはずだ。[No.409]"),
("I'll bet (that) he's coming.","きっと彼は来ると思う。[No.410]"),
("demand an apology.","謝罪を要求する。[No.411]"),
("have a strong desire to study in the U.K.","イギリスに留学したいという強い願望をもつ。[No.412]"),
("praise the man for his diligence.","その男の勤勉さを褒める。[No.413]"),
("It's an honor to be here.","お招き頂き有り難うございます。[No.414]"),
("chat over the tea.","お茶を飲みながらおしゃべりをする。[No.415]"),
("refer to my childhood.","私の子供の頃について触れる。[No.416]"),
("You'd better not mention it.","それには触れないほうがいい。[No.417]"),
("convey my feelings by touching her hand.","彼女の手に触れて、気持ちを伝える。[No.418]"),
("emphasize the importance of breakfast.","朝食の重要性を強調する。[No.419]"),
("greatly exaggerate a story.","話をとても大げさに言う。[No.420]"),
("I asked him why, but he didn't reply.","彼になぜかと尋ねたが、彼は返事をしなかった。[No.421]"),
("respond to a question.","質問に回答する。[No.422]"),
("whisper in her ear.","彼女の耳元でささやく。[No.423]"),
("his casual remark.","彼の何気なく言った発言。[No.424]"),
("observe the behavior of the birds.","鳥の行動を観察する。[No.425]"),
("Your plan is excellent in theory.","あなたの計画は理論上は素晴らしい。[No.426]"),
("handwriting analysis.","筆跡鑑定（分析）。[No.427]"),
("natural phenomena.","自然現象。[No.428]"),
("a drone with a GPS device.","GPS装置を搭載したドローン。[No.429]"),
("carry out a chemical experiment.","化学の実験をする。[No.430]"),
("chemicals that are harmful to the environment.","環境に有害な化学物質。[No.431]"),
("burn fossil fuels.","化学燃料を燃やす。[No.432]"),
("a nuclear power plant.","原子力発電所。[No.433]"),
("statistics show that younger people prefer football to baseball.","統計によると、若年層は野球よりサッカーを好むそうだ。[No.434]"),
("pursue a career in journalism.","報道関係の道に進む。[No.435]"),
("accomplish this task.","この仕事をやり遂げる。[No.436]"),
("overcome my shyness.","私の内気なところを克服する。[No.437]"),
("fulfill a childhood dream.","子どもの頃の夢を果たす。[No.438]"),
("devote my life to helping others.","人助けに人生を捧げる。[No.439]"),
("strive to cut costs.","経費削減に努力する。[No.440]"),
("aim to finish by Wednesday.","水曜日までに終わらせるつもりだ。[No.441]"),
("face a big challenge.","大きな課題に直面する。[No.442]"),
("by trial and error.","試行錯誤で。[No.443]"),
("I felt dizzy when I stood up.","立ち上がった時にめまいがした。[No.444]"),
("have a hearty appetite.","食欲が旺盛だ。[No.445]"),
("A lot of people are starving to death in Africa.","アフリカでは多くの人が餓死している。[No.446]"),
("mental and physical health.","心身の健康。[No.447]"),
("take a rest.","(ちょっと)休憩する。[No.448]"),
("have heart bypass surgery.","心臓バイパス手術を受ける。[No.449]"),
("the risk of heart disease.","心臓病のリスク。[No.450]"),
("drop out of the race because of a sudden stomachache.","突然の腹痛でレースを棄権する。[No.451]"),
("show the symptoms of heatstroke.","熱中症の症状が現れる。[No.452]"),
("get cancer.","がんになる。[No.453]"),
("fire engines and ambulances.","消防車と救急車。[No.454]"),
("recover from a heart attack.","心臓発作から回復する。[No.455]"),
("have a sore throat from a cold.","かぜでのどが痛い。[No.456]"),
("My eyelids swelled up.","まぶたが腫れ上がった。[No.457]"),
("cough loudly.","大きく咳をする。[No.458]"),
("My nose has started to bleed.","鼻血が出てきた。[No.459]"),
("faint pencil lines.","かすかな鉛筆の跡。[No.460]"),
("I am exhausted from walking all day.","1日中歩いてくたくただ。[No.461]"),
("cure you of your disease.","あなたの病気を治す。[No.462]"),
("He is physically disabled.","彼は身体に障がいがある。[No.463]"),
("Desk work gives me a stiff back.","デスクワークで腰が痛い。[No.464]"),
("develop my arm muscles.","腕の筋肉をつける。[No.465]"),
("stick my tongue out at him.","彼にあかんべえをする。[No.466]"),
("lose my sense of time.","時間の感覚をなくす。[No.467]"),
("wipe the sweat off my forehead.","額の汗をぬぐう。[No.468]"),
("regardless of age or gender.","年齢、性別とは無関係に。[No.469]"),
('"What is your nationality?" "I’m Japanese."',"「あなたの国籍は？」 「日本です（日本人です）。」[No.470]"),
("the population of senior citizens.","高齢者人口。[No.471]"),
("civil rights.","公民権（選挙権などの権利）。[No.472]"),
("racial discrimination.","人種差別。[No.473]"),
("show an interest in a rural lifestyle.","田舎暮らしに興味を示す。[No.474]"),
("a domestic flight.","（飛行機の）国内線。[No.475]"),
("global climate change.","世界的な気候変動。[No.476]"),
("live in the suburbs of Yokohama City.","横浜市の郊外に住む。[No.477]"),
("cross the border.","国境を越える。[No.478]"),
("take on a financial burden.","財政的な負担を負う。[No.479]"),
("have a negative impact on the tourist industry.","観光業にマイナスの影響を与える。[No.480]"),
("women's social status.","女性の社会的地位。[No.481]"),
("All people are created equal.","すべての人は平等に作られている。[No.482]"),
("have good relationships with other people.","他者との良好な人間関係をもつ。[No.483]"),
("have a good reputation for its beautiful night view.","夜景がきれいなことで評判がよい。[No.484]"),
("a trend toward hiring cheap labor.","安価な労働者を雇う風潮。[No.485]"),
("public services.","公共事業。[No.486]"),
("have a religion.","宗教を信じている。[No.487]"),
("a moral responsibility.","道徳的責任。[No.488]"),
("meet our safety standard.","私たちの安全基準を満たす。[No.489]"),
("bring prosperity of our country.","我が国に繁栄をもたらす。[No.490]"),
("face a serious economic crisis.","深刻な経済危機に直面する。[No.491]"),
("end racial prejudice.","人種的偏見を終わらせる。[No.492]"),
("fight racial discrimination.","人種差別と戦う。[No.493]"),
("do a lot of work for charity.","多くの慈善活動を行う。[No.494]"),
("Tourism has brought great benefits to this village.","観光がこの村に多大な恩恵をもたらした。[No.495]"),
("work for social welfare.","社会福祉のために働く。[No.496]"),
("the Polish community in the U.K.","イギリスのポーランド人社会。[No.497]"),
("each individual's right to privacy.","各個人のプライバシーの権利。[No.498]"),
("a government official.","政府の役人。[No.499]"),
("immigrants from India.","インドからの移民。[No.500]"),
("take part in volunteer activities.","ボランティア活動に参加する。[No.501]"),
("interact well with other students.","ほかの生徒とうまく付き合う。[No.502]"),
("contribute to world peace.","世界平和に貢献する。[No.503]"),
("abolish capital punishment.","死刑制度を廃止する。[No.504]"),
("The government should impose a total ban on cigarette advertising.","政府はタバコの広告を全面禁止すべきだ。[No.505]"),
("have free access to a computer.","コンピュータを自由に利用できる。[No.506]"),
("fulfill my duties.","義務を果たす。[No.507]"),
("I am responsible for what happens at school.","私には学校で起きることに対して責任がある。[No.508]"),
("China's one-child policy.","中国の一人っ子政策。[No.509]"),
("I was elected a class representative.","私はクラス委員に選ばれた。[No.510]"),
("commerce and industry.","商工業。[No.511]"),
("my monthly income.","私の月収。[No.512]"),
("The restaurant's daily profit is about $1,000.","そのレストランの1日の利益はおよそ1000ドルだ。[No.513]"),
("pay taxes on my income.","収入に課された税金を払う。[No.514]"),
("This money will cover all your expenses.","このお金があなたのすべての費用をまかなうだろう。[No.515]"),
("pay back a debt of 100 dollars.","100ドルの借金を返す。[No.516]"),
("have a large deposit in the bank.","銀行に多額の預金がある。[No.517]"),
("Goods are delivered free of charge.","商品は無料でお届けします。[No.518]"),
("get a daily wage of $100.","日給100ドルを得る。[No.519]"),
("close down my inn because of the continuing recession.","長引く不況のため旅館を閉める。[No.520]"),
("consume a large amount of electricity.","大量の電気を消費する。[No.521]"),
("Don't waste so much time on video games.","テレビゲームにそんなに多くの時間を浪費してはいけません。[No.522]"),
("invest one million yen in stocks.","株に100万円を投資する。[No.523]"),
("import beef from the U.S.","アメリカから牛肉を輸入する。[No.524]"),
("receive financial support.","経済的支援を受ける。[No.525]"),
("hire movers to do all the work.","引越し業者を雇って全部任せる。[No.526]"),
("employ minors.","未成年を雇う。[No.527]"),
("resign as coach.","コーチを辞める。[No.528]"),
("qualify for bank loans.","銀行ローンを受ける資格がある。[No.529]"),
("assign that important job to him.","彼にその大切な仕事を割り当てる。[No.530]"),
("my name, address, and occupation.","氏名、住所、職業。[No.531]"),
("start a career as a doctor.","医者として働き始める。[No.532]"),
("enter the legal profession.","法律関係の仕事に就く。[No.533]"),
("an unemployment problem.","失業問題。[No.534]"),
("look over the documents.","資料に目を通す。[No.535]"),
("the toy (department).","おもちゃ売り場。[No.536]"),
("the branch of this bank.","この銀行の支店。[No.537]"),
("a recommended retail price.","希望小売り価格。[No.538]"),
("a colleague from work.","会社の同僚。[No.539]"),
("the tax system.","税制。[No.540]"),
("a wooden structure.","木造建造物。[No.541]"),
("study architecture.","建築（様式）を勉強する。[No.542]"),
("The new city hall is under construction.","新しい市役所が建築中です。[No.543]"),
("bodily functions.","身体の機能。[No.544]"),
("the surface of the moon.","月面（月の表面）。[No.545]"),
("learn about various aspects of Japanese culture.","日本文化のさまざまな側面を学ぶ。[No.546]"),
("sit on the edge of the bed.","ベッドの端に座る。[No.547]"),
("the makeup of the team.","そのチームの構成。[No.548]"),
("The audience consisted mainly of the young people.","観客は大半が若者だった。[No.549]"),
("Water is composed of hydrogen and oxygen.","水は水素と酸素から構成される。[No.550]"),
("attach a file to email.","Eメールにファイルを添付する。[No.551]"),
("connect the printer to my PC.","パソコンにプリンターを接続する。[No.552]"),
("These two events are closely related.","これら2つの出来事は密接に関連している。[No.553]"),
("associate brand names with high quality.","ブランド名から高品質を連想する。[No.554]"),
("stick posters on the wall.","壁にポスターを貼る。[No.555]"),
("A thief broke into the building.","泥棒がその建物に侵入した。[No.556]"),
("combat[fight] crime.","犯罪と戦う。[No.557]"),
("his motive for the crime.","彼の犯行の動機。[No.558]"),
("severely punish him for breaking the rules.","規則を破ったことに対して彼を厳しく罰する。[No.559]"),
("violate international law.","国際法を破る。[No.560]"),
("In Japan, the current legal drinking age is 20.","日本では現在、飲酒が許されているのは20歳からです。[No.561]"),
("fight with the enemy.","その敵と戦う。[No.562]"),
("a conflict between two parties.","2つの政党の間の対立。[No.563]"),
("compete with each other for good grades.","良い成績を目指してお互いに競い合う。[No.564]"),
("Our team was completely defeated.","私たちのチームは完敗した。[No.565]"),
("Over 30 people fell victim to the terrorist attack.","30名以上の人がそのテロの犠牲になった。[No.566]"),
("remove an obstacle to an agreement.","合意への障害を取り除く。[No.567]"),
("Smoking does you harm.","喫煙は害を及ぼす。[No.568]"),
("invade our privacy.","私たちのプライバシーを侵害する。[No.569]"),
("endanger the lives of the passengers.","乗客の生命を危険にさらす。[No.570]"),
("The meeting was temporarily interrupted by a blackout.","停電のため会議は一時中断した。[No.571]"),
("Ben's sudden arrival spoiled our plans.","ベンが突然来たので私たちの計画が台無しになった。[No.572]"),
("The football match attracted more than 10,000 spectators.","そのサッカーの試合には1万人以上の観客が押し寄せた。[No.573]"),
("one of my relatives.","親戚の1人。[No.574]"),
("the flight's departure.","飛行機の出発。[No.575]"),
("get to my destination.","目的地に到着する。[No.576]"),
("by public transportation.","公共交通機関で。[No.577]"),
("emergency vehicles.","緊急車両。[No.578]"),
("How many pieces of baggage can I take on the airplane with me?","機内へは手荷物は何個まで持ち込むことができますか。[No.579]"),
("fly to Zurich via Hong Kong.","香港経由でチューリッヒに飛ぶ。[No.580]"),
("Laziness leads to failure.","怠けると失敗する。[No.581]"),
("The sun rises in the east.","太陽は東から昇る。[No.582]"),
("This river flows into the Pacific.","この川は太平洋に流れ込む。[No.583]"),
("Japan's economic bubble burst in the 1990s.","日本のバブル経済は1990年代にはじけた。[No.584]"),
("The ice cream quickly melted.","アイスクリームはすぐに溶けてしまった。[No.585]"),
("commute (to work) by train.","電車を使って通勤する。[No.586]"),
("accompany my boss to Germany.","上司に同行してドイツに行く。[No.587]"),
("emit greenhouse gas.","温室効果ガスを排出する。[No.588]"),
("make great progress in English.","英語が随分と上達する。[No.589]"),
("advances in technology.","科学技術の進歩。[No.590]"),
("deal with the drunk well.","その酔っ払いをうまく扱う。[No.591]"),
("handle stress well.","ストレスにうまく対処する。[No.592]"),
("treat children fairly.","公平に子供を扱う。[No.593]"),
("find a clue to his whereabouts.","彼の居所の手がかりを見つける。[No.594]"),
("restrict the amount of carbohydrate.","炭水化物の量を制限する。[No.595]"),
("limit class size to fifteen.","クラスの人数を15名に制限する。[No.596]"),
("forbid employees to accept tips from customers.","従業員が客からのチップを受け取ることを禁じる。[No.597]"),
("impose a total ban on smoking in public places.","公共の場所での喫煙を全面的に禁止する。[No.598]"),
("refuse to listen to him.","彼の話を聞くことを拒む。[No.599]"),
("reject the idea.","その考えを拒絶する。[No.600]"),
("It is no use trying to persuade him to eat carrots.","ニンジンを食べるよう彼を説得するのは無駄だ。[No.601]"),
("convince him that I am right.","私が正しいことを彼に確信させる。[No.602]"),
("His remark inspired me to study.","彼の発言で私の勉強のスイッチが入った。[No.603]"),
("discourage her from buying expensive clothes.","彼女に高い服を買うのを思いとどまらせる。[No.604]"),
("promote healthy eating habits.","健全な食生活を促進する。[No.605]"),
("boost the team's morale.","チームの士気を高める。[No.606]"),
("Water expands when it freezes.","水は凍ると膨張する。[No.607]"),
("extend the deadline by one week.","締め切りを1週間延ばす。[No.608]"),
("Travel broadens your mind.","旅は視野を広げてくれる。[No.609]"),
("spread a handkerchief over my lap.","ひざの上にハンカチを広げる。[No.610]"),
("tie up old magazines with string.","ひもで古雑誌を縛る。[No.611]"),
("fasten my seat belt.","シートベルトを締める。[No.612]"),
("fix the camera to the tripod.","カメラを三脚に固定する。[No.613]"),
("install a vending machine in the school cafeteria.","学生食堂に自動販売機を設置する。[No.614]"),
("cannot resist buying new shoes.","ついつい新しい靴を買ってしまう。[No.615]"),
("obey my parents.","親の言うことに従う。[No.616]"),
("engage in relief operations.","救援活動に従事する。[No.617]"),
("bump into a pile of books.","本の山にぶつかる。[No.618]"),
("bend down to pick up the pen.","ペンを拾い上げるために腰をかがめる。[No.619]"),
("The players hugged each other tightly.","選手たちは互いにしっかり抱き合った。[No.620]"),
("stare at a computer screen.","コンピュータの画面をじっと見つめる。[No.621]"),
("gaze at the ceiling.","天井を見つめる。[No.622]"),
("glance at the clock.","時計をちらっと見る。[No.623]"),
("glimpse her face.","彼女の顔がちらりと見える。[No.624]"),
("stretch my arms.","腕を伸ばす。[No.625]"),
("stumble over a rock.","石につまづく。[No.626]"),
("press the button.","ボタンを押す。[No.627]"),
("drag the table into the kitchen.","台所までそのテーブルを引きずる。[No.628]"),
("lean against the wall.","壁にもたれる。[No.629]"),
("scratch my back.","背中をかく。[No.630]"),
("bow to each other.","お互いにおじぎをする。[No.631]"),
("She nodded and smiled.","彼女はうなずき、微笑んだ。[No.632]"),
('He sighed saying, "You win."',"「降参」と言って彼はため息をついた。[No.633]"),
("stretch and yawn loudly.","伸びをして大きな声であくびをする。[No.634]"),
("Cover your mouth when you sneeze.","くしゃみするときには口を覆いなさい。[No.635]"),
("bury a time capsule at the foot of the cherry tree.","桜の木の根元にタイムカプセルを埋める。[No.636]"),
("perform difficult tasks.","困難な仕事を遂行する。[No.637]"),
("adopt his plan.","彼の計画を採用する。[No.638]"),
("escape from the burning house.","燃え盛る家から逃げる。[No.639]"),
("His clothes were scattered all over the floor.","彼の服が床中に脱ぎ散らかされていた。[No.640]"),
("fold the paper along the dotted line.","点線に添って紙を折る。[No.641]"),
("hang the washing on the pole.","物干しざおに洗濯物を掛ける。[No.642]"),
("release the hostages.","人質を解放する。[No.643]"),
("strike him on the cheek.","彼のほほを打つ。[No.644]"),
("beat a drum.","太鼓をたたく。[No.645]"),
("protect our skin from the sun.","日差しから肌を守る。[No.646]"),
("twist a wire.","針金をねじ曲げる。[No.647]"),
("skip cram school.","塾をサボる。[No.648]"),
("Children should be exposed to different culture.","子どもは様々な文化に触れるべきだ。[No.649]"),
("stir my coffee with a spoon.","スプーンでコーヒーを混ぜる。[No.650]"),
("Don't shake the bottle of soda water.","炭酸の瓶を振るな。[No.651]"),
("polish my glasses with a piece of cloth.","布で眼鏡を磨く。[No.652]"),
("attend my sister's wedding.","姉の結婚式に出席する。[No.653]"),
("imitate the American teacher's English.","そのアメリカ人教師の英語をまねる。[No.654]"),
("conduct research.","研究を行う。[No.655]"),
("struggle to bring up my children.","子どもを育てるのに苦労する。[No.656]"),
("Kinkakuji Temple has burned down several times.","金閣寺は何度か焼け落ちている。[No.657]"),
("cheat in an exam.","試験でカンニングをする。[No.658]"),
("participate in the National Sports Festival.","国体に参加する。[No.659]"),
("believe that Santa Claus exists.","サンタクロースは存在すると信じる。[No.660]"),
("Several problems arose.","いくつかの問題が生じた。[No.661]"),
("The accident occurred at this intersection at about 10 p.m.","その事故は午後10時ごろこの交差点で起きた。[No.662]"),
("I was involved in a traffic accident.","交通事故に巻き込まれた。[No.663]"),
("This job requires many year's experience.","この仕事には長年の経験が必要だ。[No.664]"),
("The Japanese officials discussed the issue with their French counterparts.","日本政府高官はフランス政府の高官とその問題について話し合った。[No.665]"),
("the advent of new technology.","新技術の到来。[No.666]"),
("maintain proper work-life balance.","適切なワークライフバランスを維持する。[No.667]"),
("The meeting lasted (for) three hours.","会議は3時間続いた。[No.668]"),
("If your fever persists, you should see a doctor.","熱が続くようなら、医者に行ったほうがいい。[No.669]"),
("examine the old records.","古い記録を調べる。[No.670]"),
("I have gained five kilos.","5キロ太った。[No.671]"),
("obtain a work visa.","就労ビザを得る。[No.672]"),
("acquire a foreign language.","外国語を習得する。[No.673]"),
("search the house for my earrings.","イヤリングがないか家を捜す。[No.674]"),
("logical thinking.","論理的な思考。[No.675]"),
("study abroad on a scholarship.","奨学金で留学する。[No.676]"),
("follow the on-screen instructions.","画面上の指示に従う。[No.677]"),
("People's lifestyles are often determined by their incomes.","人々の生活スタイルは収入で決まることが多い。[No.678]"),
("conclude that the factory should be closed.","その工場は閉鎖すべきだと結論を下す。[No.679]"),
("distinguish sheep from goats.","ヒツジをヤギと区別する。[No.680]"),
("classify the books according to subject.","テーマで図書を分類する。[No.681]"),
("It is estimated that this shrine is over 500 years old.","この神社の歴史は500年以上だと見積もられている。[No.682]"),
("organize my thoughts before speaking.","話す前に私の考えをまとめる。[No.683]"),
("Do you recognize me?","私が誰だかわかりますか。[No.684]"),
("You are supposed to take off your shoes at the door.","玄関では靴を脱ぐことになっています。[No.685]"),
("assume that all people are the same.","人間は皆同じだと思い込む。[No.686]"),
("I don't care about trivial matters.","私は細かいことを気にしません。[No.687]"),
("Her parents approved of her marriage.","彼女の両親は彼女の結婚を認めた。[No.688]"),
("I noticed that there was a hole in my sock.","靴下に穴が空いていることに気がついた。[No.689]"),
("I am aware that my time on earth is limited.","この世の時間には限りがあると気づいている。[No.690]"),
("I was conscious of the fact that it was an important meeting.","それが重要な会議であることは意識していた。[No.691]"),
("The professor is concerned with environmental problems.","その教授は環境問題に関心を持っている。[No.692]"),
("Zack was born in the U.S. but he regards Japan as his home.","ザックはアメリカ生まれだが、日本を故郷だと思っている。[No.693]"),
("We are fully committed to the project.","私たちはその計画に専念している。[No.694]"),
("I have never once doubted him.","彼のことを疑ったことは一度もない。[No.695]"),
("memorize the times tables.","九九を暗記する。[No.696]"),
("forgive him for what he said.","彼の発言に対して彼を許す。[No.697]"),
("take cars for granted.","車の存在を当然のものと考える。[No.698]"),
("I recalled that I had seen him cheating on the test.","彼がテストでカンニングするのを目撃したことを思い出した。[No.699]"),
("broaden my outlook on life.","人生観を広げる。[No.700]"),
("get a fresh perspective.","新たな視点を得る。[No.701]"),
("abandon my dream of studying abroad.","留学する夢を諦める。[No.702]"),
("eliminate gender discrimination.","性差別をなくす。[No.703]"),
("get rid of my old toys.","古いおもちゃを処分する。[No.704]"),
("Illegally parked bicycles will be removed.","放置自転車は撤去される。[No.705]"),
("develop natural resources.","天然資源を開発する。[No.706]"),
("conservation groups.","環境保護団体。[No.707]"),
("preserve endangered species.","絶滅危惧種を保護する。[No.708]"),
("natural disasters in Japan.","日本の自然災害。[No.709]"),
("creatures from another planet.","別の惑星から来た生き物。[No.710]"),
("the natural environment.","自然環境。[No.711]"),
("The sun appeared on the horizon.","太陽が水平線上に現れた。[No.712]"),
("the ozone layer.","オゾン層。[No.713]"),
("organic agriculture.","有機農業。[No.714]"),
("the main crops in this area.","この地域の主要な農産物。[No.715]"),
("cultivate the soil.","土を耕す。[No.716]"),
("pull up weeds.","雑草を抜く。[No.717]"),
("Pollen levels are high today.","今日は花粉の量が多い。[No.718]"),
("he almost drowned, but luckily he was saved.","彼は溺れかけたが、幸い救助された。[No.719]"),
("This roof leaks.","雨漏りがする（この屋根は濡れる）。[No.720]"),
("This town has a mild[harsh] climate.","この町の気候は温暖［過酷］です。[No.721]"),
("ice crystals in the atmosphere.","大気中の氷の結晶。[No.722]"),
("according to the weather forecast.","天気予報によれば。[No.723]"),
("Kyoto is hot and humid in summer.","京都は夏は蒸し暑い。[No.724]"),
("tropical rainforests.","熱帯雨林。[No.725]"),
("install solar panels on the roof.","屋根にソーラーパネルを取り付ける。[No.726]"),
("elephants and other endangered species.","ゾウなどの絶滅危惧種。[No.727]"),
("spray crops with pesticide.","作物に農薬を散布する。[No.728]"),
("Dinosaurs became extinct millions of years ago.","恐竜は何百万年も前に絶滅した。[No.729]"),
("feed these goldfish.","これらの金魚にえさを与える。[No.730]"),
("energetic boys and girls.","活発な少年少女たち。[No.731]"),
("A greedy child ate all the pies.","食い意地の張った子がパイを全部食べた。[No.732]"),
("a brave firefighter.","勇敢な消防士。[No.733]"),
("leave a generous tip.","気前よくチップを置く。[No.734]"),
("intellectual property.","知的財産。[No.735]"),
("Babies are curious about everything.","赤ん坊はすべての物に好奇心が強い。[No.736]"),
("Children are very imaginative.","子どもは非常に想像力が豊かだ。[No.737]"),
("I cannot afford to buy a new car.","新車を買う余裕がない。[No.738]"),
("Beth is eager to buy a fur coat.","ベスは毛皮のコートを買いたがっている。[No.739]"),
("Don't be selfish.","自分勝手なことをしてはだめだよ。[No.740]"),
("Her attitude suddenly became aggressive.","彼女の態度が突然攻撃的になった。[No.741]"),
("Never be cruel to animals.","動物を残酷に扱うな。[No.742]"),
("Lucy is addicted to her smartphone.","ルーシーはスマホ（スマートフォン）中毒である。[No.743]"),
("a stubborn old man.","頑固な老人。[No.744]"),
("a dress with a bold design.","大胆なデザインの服。[No.745]"),
("feel guilty about lying to her.","彼女にうそをついたことを申し訳なく思う。[No.746]"),
("Jack is innocent of the crime.","ジャックはその犯罪に関して無実だ。[No.747]"),
("make a sincere effort.","ひたむきな（誠実な）努力をする。[No.748]"),
("Paul is modest about his success.","ポールは成功を鼻にかけない。[No.749]"),
("make a stupid mistake.","ばかな間違いをする。[No.750]"),
("Rick is indifferent to politics.","リックは政治に無関心だ。[No.751]"),
("Japanese trains are extremely punctual.","日本の列車は非常に時間に正確だ。[No.752]"),
("My son is a coward when it comes to going to the dentist.","息子は歯医者に行くことにかけては臆病者です。[No.753]"),
("Each plane has to follow a precise route.","どの飛行機も正確な航路をたどらなくてはならない。[No.754]"),
("an accurate map.","正確な地図。[No.755]"),
("the proper use of chopsticks.","箸の正しい使い方。[No.756]"),
("keep the office tidy.","事務所をきちんとしておく。[No.757]"),
("an efficient method of transporting goods.","商品を輸送する能率的な方法。[No.758]"),
("What you're saying is reasonable.","あなたの言っていることはもっともだ。[No.759]"),
("a historical significant event.","歴史的に重要な出来事。[No.760]"),
("Don't waste your precious time.","貴重な時間を浪費するな。[No.761]"),
("Water is essential to living things.","水は生物にとって不可欠だ。[No.762]"),
("make a fundamental change.","根本的な改革を行う。[No.763]"),
("The advantages outweigh the disadvantages.","メリットがデメリットを上回る。[No.764]"),
("in a critical condition.","危篤状態（危機的な状況）で。[No.765]"),
("do serious damage to the environment.","環境に深刻な打撃を与える。[No.766]"),
("a highly complex process.","非常に複雑な過程。[No.767]"),
("make things complicated[×complex].","事態を複雑にする。[No.768]"),
("the delicate question of salary.","給与という繊細な問題。[No.769]"),
("write in plain English.","平易な英語で書く。[No.770]"),
("It was obvious that she was unwell.","彼女の体調がすぐれないのは明白だった。[No.771]"),
("make remarkable progress.","注目すべき進歩を遂げる。[No.772]"),
("an outstanding shogi player.","傑出した棋士。[No.773]"),
("various ideas.","さまざまな考え。[No.774]"),
("the diversity of life on earth.","地球上の生物の多様性。[No.775]"),
("What sort of soap do you use?.","どのような（種類の）石けんを使っているの。[No.776]"),
("have a marvelous memory.","驚くべき記憶力を持っている。[No.777]"),
("lead an active school life.","活動的な学生生活を送る。[No.778]"),
("positive thinking.","前向きな考え。[No.779]"),
("a pure wool blanket.","100％（純粋な）ウールの毛布。[No.780]"),
("make steady progress.","着実に進歩する（着実な進歩をする）。[No.781]"),
("Jim is flexible about everything.","ジムはあらゆることに柔軟に対応する。[No.782]"),
("a ripe mango.","熟したマンゴー。[No.783]"),
("His temperature remains stable.","彼の体温は安定している。[No.784]"),
("the negative aspects of aging.","歳をとることの否定的な側面。[No.785]"),
("a vague description.","曖昧な説明。[No.786]"),
("Steve is a little weird","isn't he?.[No.787]"),
("a rough road.","でこぼこの道。[No.788]"),
("severe criticism.","厳しい評判。[No.789]"),
("He is quite passive","and never speaks out.[No.790]"),
("His effort was in vain.","彼の努力は無駄になった。[No.791]"),
("a fake diamond.","偽物のダイヤモンド。[No.792]"),
("It is risky to buy a used car from a private seller.","個人の売り手から中古車を買うのは危険だ。[No.793]"),
("an odd habit.","奇妙な習慣。[No.794]"),
("Doris is ignorant of the world.","ドリスは世間知らずだ（世間について無知だ）。〔No.794〕)[No.795]"),
("the contrast between the two.","その両者の対比。[No.796]"),
("a valid reason.","妥当な理由。[No.797]"),
("collect rate stamps.","珍しい切手を集める。[No.798]"),
("feel more relaxed in casual clothes.","ふだん着（気楽な服）のほうが落ち着く。[No.799]"),
("This T-shirt is available in all sizes.","このTシャツはすべてのサイズでご用意できます（手に入る）。[No.800]"),
("gain practical experience.","実践経験を積む。[No.801]"),
("an abstract work of art.","抽象的な芸術作品。[No.802]"),
("brand-new climbing boots.","新品の登山靴。[No.803]"),
("buy secondhand clothes cheaply.","古着を安く買う。[No.804]"),
("rapid economic growth.","急速な経済成長。[No.805]"),
("There is an urgent need for more nursery schools.","もっと多くの保育所が緊急に必要だ（もっと多くの保育所に対する緊急の必要性がある）。[No.806]"),
("a shallow bathtub.","浅い浴槽。[No.807]"),
("a sharp increase in prices.","急激な物価の上昇。[No.808]"),
("The supporters stayed calm.","サポーターたちは落ち着いていた。[No.809]"),
("swim naked in the river.","川で裸で（裸の状態で）泳ぐ。[No.810]"),
("I am independent of my parents.","私は両親の世話になっていない（両親から独立している）。[No.811]"),
("a tense atmosphere in the waiting room.","待合室の張りつめた雰囲気。[No.812]"),
("a narrow mountain path.","狭い山道。[No.813]"),
("The seat next to mine was vacant.","私の隣の席は空いていた。[No.814]"),
("have vivid memories of my time in Sydney.","シドニーで過ごした日々の鮮明な思い出が残っている。[No.815]"),
("the awkward movements of the robot.","そのロボットのぎこちない動き。[No.816]"),
("Historians try to be objective.","歴史家は客観的になるように努める。[No.817]"),
("manual work.","手仕事。[No.818]"),
("The twins are very alike.","その双子はとてもよく似ている。[No.819]"),
("a custom that is alien to me.","私にとって異質な慣習。[No.820]"),
("Women tend to count calories more than men do.","女性は男性よりカロリー計算をする傾向がある。[No.821]"),
("Msato has trained so hard that he deserves to win.","マサトは一生懸命トレーニングしたので、勝ってもおかしくない（勝つことに値する）。[No.822]"),
("glass fragments.","ガラスの破片。[No.823]"),
("a wide range of topics.","幅広い話題。[No.824]"),
("do business on a large scale.","手広く（大規模に）商売をする。[No.825]"),
("This custom is unique to Japan.","この習慣は日本特有のものだ。[No.826]"),
("a particular situation.","ある特定の状況。[No.827]"),
("a typical Japanese-style breakfast.","典型的な日本の朝食。[No.828]"),
("the general public.","一般大衆。[No.829]"),
("the lives of ordinary people.","庶民（ふつうの人々）の生活。[No.830]"),
("Middle-aged and older people account for 70 % of the group.","中高年がその集団の70%を占める。[No.831]"),
("calculate this month's expenses.","今月の出費を計算する。[No.832]"),
("Please measure your blood pressure.","血圧を測ってください。[No.833]"),
("Educational standards are declining.","教育水準が下がっている。[No.834]"),
("Let's split the bill.","割り勘にしよう（勘定を割る）。[No.835]"),
("the volume of a cylinder.","円柱の体積。[No.836]"),
("The proportion of boys to girls in my school is five to one.","私の学校の男女比は5：1だ。[No.837]"),
("two dozen eggs.","2ダースの卵。[No.838]"),
("a large amount of fat.","大量の脂肪。[No.839]"),
("a huge mass of data.","非常に多くのデータ。[No.840]"),
("There is a water shortage in this area.","この地域は水が不足している。[No.841]"),
("an enormous amount of time.","莫大な（量の）時間。[No.842]"),
("in my spare time.","余分な時間で。[No.843]"),
("arrange for someone to drive her home.","誰かが彼女を家まで車で送ってくれるよう手配する。[No.844]"),
("adapt to a new school life.","新しい学校生活に適応する。[No.845]"),
("This sweater matches your skirt.","このセーターは君のスカートによく合っている。[No.846]"),
("This dress fits you.","このワンピースは（サイズが）君にぴったりだ。[No.847]"),
("An emergency has arisen.","緊急事態が生じた。[No.848]"),
("on this occasion.","このような場合には。[No.849]"),
("an accidental meeting","偶然の出会い。[No.850]"),
("the current energy crisis.","現在のエネルギー問題。[No.851]"),
("a temporary license.","仮免許。[No.852]"),
("a permanent member of the U.N. Security Council.","国連安全保障理事会の常任理事国。[No.853]"),
("the previous morning.","（ある日の）前日の朝（前の朝）。[No.854]"),
("the former and the latter.","前者と後者。[No.855]"),
("contemporary literature.","現代文学。[No.856]"),
("Have you seen him lately?.","最近彼と会った。[No.857]"),
("immediately after breakfast.","朝食後すぐに。[No.858]"),
("The deadline for entries is next Monday.","登録の締め切りは次の月曜日だ。[No.859]"),
("decades of research.","数十年にわたる研究。[No.860]"),
("supply people with drinking water.","人々に飲み水を供給する。[No.861]"),
("AI has replaced humans in many fields.","人工知能が多くの分野で人間に取って代わった。[No.862]"),
("exchange Japanese yen for U.S. dollars.","日本円を米ドルと交換する。[No.863]"),
("substitute honey for sugar.","砂糖の代わりにはちみつを使う。[No.864]"),
("submit an application form.","申込用紙を提出する。[No.865]"),
("an alternative to nuclear power.","原子力の代わりになるもの。[No.866]"),
("deliver pizzas.","ピザを配達する。[No.867]"),
("enclose several photos.","何枚かの写真を同封する。[No.868]"),
("put a stamp on the envelope.","封筒に切手を貼る。[No.869]"),
("play tricks on Kevin.","ケビンにいたずらをする。[No.870]"),
("carry a heavy load on my back.","重い荷物を背負う。[No.871]"),
("the contents of her bag.","彼女のかばんの中身。[No.872]"),
("a survey of 2","000 households.[No.873]"),
("antibacterial goods.","抗菌グッズ。[No.874]"),
("spend a lot of money on luxuries.","ぜいたく品に多額のお金を使う。[No.875]"),
("Do you accept credit cards?.","クレジットカードは使えますか。[No.876]"),
("a survey using a questionnaire.","アンケート（を用いた）調査。[No.877]"),
("make a reservation under the name of Sophie.","ソフィーの名前で予約する。[No.878]"),
("make a fuss about trivial things.","くだらないことで大騒ぎする。[No.879]"),
("the reward for the job.","その仕事に対する報酬。[No.880]"),
("have a farewell party.","送別会を開く。[No.881]"),
("receive a warm reception.","暖かい歓迎を受ける。[No.882]"),
("a large portion of roast beef.","大盛りのローストビーフ。[No.883]"),
("cook","clean[No.884]"),
("I'll just take a little nap.","ちょっと昼寝をします。[No.885]"),
("I woke up at six a.m.","but did not get up.[No.886]"),
("a soft drink vending machine.","清涼飲料水の自動販売機。[No.887]"),
("a local grocery (store).","地元の食料雑貨店。[No.888]"),
("I have an appointment to see the dentist at five.","5時に歯医者の予約を入れている。[No.889]"),
("You'd better consult your doctor.","医者に診てもらいなさい。[No.890]"),
("Koyasan is registered as a World Heritage Site.","高野山は世界遺産に登録されている。[No.891]"),
("dye my hair brown.","髪を茶色に染める。[No.892]"),
("subscribe to the magazine.","雑誌を定期購読する。[No.893]"),
("Freedom of speech is guaranteed under the Constitution of Japan.","言論の自由は日本国憲法で保証されている。[No.894]"),
("wipe the table.","テーブルを拭く。[No.895]"),
("sweep the floor with a broom.","ほうきで床を掃く。[No.896]"),
("transfer at Rome.","ローマで乗り換える。[No.897]"),
("They have divorcerd.","彼らは離婚した。[No.898]"),
("A terrible fate awaited them.","恐ろしい運命が彼らを待ち受けていた。[No.899]"),
("It was his destiny to save his nation.","国を救うことが彼の運命だった。[No.900]"),
("ice crem with a green tea flavor.","抹茶味のアイスクリーム。[No.901]"),
("the perfume of roses.","バラの香り。[No.902]"),
("the ingredients of lasagne.","ラザニアの材料。[No.903]"),
("a bitter experience.","つらい経験。[No.904]"),
("prefer an aisle seat to a window seat.","窓側の席より通路側の席のほうが好き。[No.905]"),
("keep track of my schedule.","スケジュール管理をする（スケジュールの経過を追う）。[No.906]"),
("an election district.","選挙区。[No.907]"),
("indoor sports facilities.","室内スポーツ施設。[No.908]"),
("line up in order of height.","身長順に並ぶ。[No.909]"),
("a distant island.","遠い島。[No.910]"),
("New Mexico is located 2","240 meters above sea level.[No.911]"),
("occupy two seats on the train.","電車で2つの席を占有する。[No.912]"),
("a msnsion surrounded by red brick walls.","赤れんがの塀に囲まれたお屋敷。[No.913]"),
("classical music.","クラシック音楽。[No.914]"),
("an advanced civilization.","高度な文明。[No.915]"),
("the cultural heritage of Japan.","日本の文化遺産。[No.916]"),
("a film script.","映画の台本。[No.917]"),
("a Japanese folk table.","日本の民話。[No.918]"),
("the Nobel Prize in Literature.","ノーベル文学賞。[No.919]"),
("9/11 was a terrible tragedy.","9/11（の同時多発テロ）は本当に悲劇だった。[No.920]"),
("learn a lot of poetry by heart.","多くの詩を暗唱する。[No.921]"),
("a biography of Helen Keller.","ヘレン・ケラーの伝記。[No.922]"),
("the term degital native.'","『デジタルネイティブ』という言葉。[No.923]"),
("As the proverb goes[says]","time flies.[No.924]"),
("speak in the Kansai dialect.","関西弁で話す。[No.925]"),
("He spesks fluent Spanish.","彼はスペイン語が流暢だ。[No.926]"),
("translate a sentence literally.","文を直訳する（文字どおりに文を訳す）。[No.927]"),
("Obesity is defined as a BMI of 30 or above.","肥満はBMI30以上と定義されている。[No.928]"),
("interpret his silence as a refusal.","彼の沈黙を拒否と解釈する。[No.929]"),
("quote a passage from the Bible.","聖書の一節を引用する。[No.930]"),
("The word bonen-kai literally means a forget-the-year party.'","「忘年会」は文字どおりには「年を忘れる会」を意味する。[No.931]"),
("Research indicates that the medicine can be harmful to children.","研究はその薬が子どもに害があるかもしれないことを示している。[No.932]"),
("reveal a secret to her.","彼女に秘密を漏らす。[No.933]"),
("announce the results of the election.","選挙の結果を発表する。[No.934]"),
("The interview with him was broadcast live.","彼のインタビューは生放送された。[No.935]"),
("prove (that) it is false.","それが偽物だと証明する。[No.936]"),
("advertise the concert.","コンサートを宣伝する。[No.937]"),
("Let me clarify my opinion.","言いたいことを明確にします。[No.938]"),
("seek specialist advice.","専門家の意見を求める。[No.939]"),
("entertain an audience.","観客を楽しませる。[No.940]"),
("The clown amused us all.","そのピエロは私たちみんなを楽しませた。[No.941]"),
("The pop star's marriage attracted media attention.","人気スターの結婚はマスコミの関心を引きつけた。[No.942]"),
("I was fascinated by the Sagrada Familia.","サグラダファミリアに魅了された。[No.943]"),
("I was absorbed in a book.","私は本に夢中になっていた。[No.944]"),
("I am very fond of ramen.","私はラーメンが大好きだ。[No.945]"),
("Oh! You scared me!.","もう、びっくりしたじゃない（あなたは私をおびえさせた）。[No.946]"),
("I was alarmed to hear a man shout.","男が叫ぶのを聞いて、びっくりした。[No.947]"),
("Sam amazed me with his cooking skills.","サムはその料理の腕で私を驚かせた。[No.948]"),
("Her habit of biting her nails irritates me.","彼女の爪をかむ癖は私をいらいらさせる。[No.949]"),
("The news upset her.","その知らせは彼女を動揺させた。[No.950]"),
("What puzzles me is why she can't understand me.","私を当惑させるのは、なぜ彼女は私の言うことが理解できないかだ。[No.951]"),
("His reply confused me.","彼の返答は私を困惑させた。[No.952]"),
("I was bored with his long speech.","彼の長い話にうんざりした。[No.953]"),
("I felt frustrated bacause I could not express myself well.","うまく表現できなくてもどかしい思いをした。[No.954]"),
("I was disappointed with the soccer game.","サッカーの試合にがっかりした。[No.955]"),
("I was embarrassed about using the wrong fork at dinner.","夕食時、フォークを使い間違えて恥ずかしかった。[No.956]"),
("I'm ashamed of hurting her feelings.","彼女の気持ちを傷つけたことを恥じている。[No.957]"),
("feel uneasy about living alone.","ひとり暮らしは不安だ。[No.958]"),
("Please do not hesitate to contact me if you have any questions.","質問があればどうぞご遠慮なく連絡して（連絡するのをためらわないで）ください。[No.959]"),
("I was reluctant to go with him.","彼と一緒に行くのは気が進まなかった。[No.960]"),
("The little girl was trembling with fear.","その少女は恐怖で震えていた。[No.961]"),
("Boast about how clever my son is.","私の息子がどれほど賢いかを自慢する。[No.962]"),
("be jealous of his promotion.","彼の昇進が妬ましい。[No.963]"),
("envy him for his wealth.","財産のことで彼を羨ましく思う。[No.964]"),
("yell at the children to be quiet.","子どもたちに静かにせよと叱る（大声で言う）。[No.965]"),
("respect Gandhi.","ガンジーを尊敬する。[No.966]"),
("a deep sense of despair.","深い絶望感。[No.967]"),
("show my emotions.","感情を表に出す。[No.968]"),
("have deep sympathy for the victims.","犠牲者たちに本当に同情する。[No.969]"),
("It's a shame that you did'nt see that movie.","あなたがその映画を見ていないのは残念です。[No.970]"),
("boost my confidence.","(私の)自信を高める。[No.971]"),
("have the courage to say no.","断る勇気を持つ。[No.972]"),
("have a passion for music.","音楽への情熱を持っている。[No.973]"),
("experience the joys and sorrows of life","人生の苦楽を経験する。[No.974]"),
("completely ignore him.","完全に彼を無視する。[No.975]"),
("His jokes offended Irish people.","彼の冗談はアイルランドの人たちを怒らせた。[No.976]"),
("The rainy weather depressed me.","雨天ですっかり気がめいってしまった（私を落ち込ませた）。[No.977]"),
("I owe my success to him.","私の成功は彼のおかげだ。[No.978]"),
("overcome my fear of snakes.","ヘビに対する恐怖を克服する。[No.979]"),
("a method for reducing stress.","ストレスを減らすやり方。[No.980]"),
("receive a great deal of media attention.","メディアにとても注目される。[No.981]"),
("a means of communication.","意思疎通の手段。[No.982]"),
("You are correct to som extent.","君はある程度正しい。[No.983]"),
("It's extremely hot outside.","外はひどく暑い。[No.984]"),
("the total cost.","総費用。[No.985]"),
("Our customers are largely women..","私たちのお客様は大部分が女性だ。[No.986]"),
("get moderate exercise.","適度な運動をする。[No.987]"),
("feel somewhat sad.","いくぶん悲しい気分だ。[No.988]"),
("a subtle difference in meaning.","かすかな意味の違い。[No.989]"),
("It will take two weeks","possibly longer.[No.990]"),
("After changing jobs many times","I eventually found a job in a bank.[No.991]"),
("Rich people are not necessarily happy.","金持ちが必ずしも幸せとは限らない。[No.992]"),
("talk frankly with a friend.","友だちと率直に話し合う。[No.993]"),
("ironically","my car was stolen right in front of the police station.[No.994]"),
("Smoking is bad for you. moreover","it costs a lot.[No.995]"),
("Hurry up; otherwise you'll be late.","急げ！さもないと遅れるぞ。[No.996]"),
("regardless of sex","race[No.997]"),
("This ring is worth over two million dollars.","この指輪は200万ドル以上の価値がある。[No.998]"),
("according to a public poll.","世論調査によると。〔[No.999]"),
("The soccer match was held","despite the heavy rain.[No.1000]"),
("purpose a new program","新しい計画を提案する[No.1001]"),
("dismiss his proposal as unrealistic","非現実的だとして彼の提案を退ける[No.1002]"),
("(God) bless you!","お大事に.（神があなたを祝福しますように）[No.1003]"),
("his glory days as a college basketball star","大学バスケットボールのスター選手としての彼の栄光の日々[No.1004]"),
("compliments on his shoes","彼の靴への褒め言葉[No.1005]"),
("the wedding feast","結婚式の宴席[No.1006]"),
("He declared that he was innocent","彼は無実だとはっきりと述べた[No.1007]"),
("highlight the issue of global warming","地球温暖化の問題を強調する[No.1008]"),
("Alex implied that he would resign","アレックスは辞意をほのめかした[No.1009]"),
("recite a poem","詩を暗唱する[No.1010]"),
("the sun's rays","太陽光線[No.1011]"),
("The workers were exposed to radiation","その労働者たちは被爆した（放射線にさらされた）[No.1012]"),
("laboratory experiments","研究室での実験[No.1013]"),
("Water is made up of oxygen and hydrogen","水は酸素と水素からできている[No.1014]"),
("a water molecule","水分子[No.1015]"),
("a chemical compound","化合物[No.1016]"),
("nerve tissue","神経組織[No.1017]"),
("remove the cancerous cells","がん細胞を除去する[No.1018]"),
("the gene for black hair","黒い髪の遺伝子[No.1019]"),
("a cancer-causing substance","発がん性物質[No.1020]"),
("solid fuel","固形燃料[No.1021]"),
("Jupiter's sixth satellite","木星の６番目の衛星[No.1022]"),
("the moon's orbit around the earth","地球を回る月の軌道[No.1023]"),
("launch a Sun probe","太陽探査機を打ち上げる[No.1024]"),
("make an attempt to break his record","彼の記録を破ろうと試みる[No.1025]"),
("have a remarkable capacity to learn language","目立った言語学習能力を有している[No.1026]"),
("The factory is capable of producing 100 cars per hour","この工場では１時間に100台もの車を生産できる[No.1027]"),
("I have attained my ideal weight","私は理想とする体重に達した[No.1028]"),
("Make a desperate effort to succeed","成功するために必死の努力をする[No.1029]"),
("She dedicated herself to her job","彼女は仕事に没頭した（仕事に自分自身を捧げた）[No.1030]"),
("Do you feel any pain?","（医者の発言）痛みはありますか[No.1031]"),
("Work under a lot of strain","過度の負担の下で働く[No.1032]"),
("A remedy for colds","かぜの治療法[No.1033]"),
("buy medicine at a nearby pharmacy","近くの薬局で薬を買う[No.1034]"),
("emergency physicians","救急医[No.1035]"),
("eating disorders","摂食障害[No.1036]"),
("Terry is three-month pregnant","テリーは妊娠3か月だ[No.1037]"),
("a clinical test","臨床試験[No.1038]"),
("Heal people by laying my hands on their bodies","体に手を当てて人々を治す[No.1039]"),
("My dog was infected with a virus","うちのイヌはウイルスに感染した（感染させられた）[No.1040]"),
("Twist my ankle","足首をひねる[No.1041]"),
("Stick up my thumb","親指を立てる[No.1042]"),
("I've got a pimple on my forehead","（私の）おでこににきびができた[No.1043]"),
("Stick out my chin","あごを突き出す（＊挑戦的態度の示唆）[No.1044]"),
("Have a chest X-ray examination","胸部のレントゲン検査を受ける[No.1045]"),
("Early detection of breast cancer","乳がんの早期発見[No.1046]"),
("The heart and the lungs","（ヒトの）心肺[No.1047]"),
("Wait for an organ transplant","臓器移植を待つ[No.1048]"),
("Have good [normal, bad] vision","視力が良い [正常だ. 悪い][No.1049]"),
("A model of the human skeleton","ヒトの骸骨の模型[No.1050]"),
("Lose all sensation in my toes","足の指先の感覚がなくなる[No.1051]"),
("Does the restaurant have a dress code?","そのレストランに服装規定はありますか[No.1052]"),
("The agenda for today's meeting","本日の会議の議題[No.1053]"),
("Fight for liberty and equality","自由と平等のために戦う[No.1054]"),
("the International Olympic Committee","国際オリンピック委員会[No.1055]"),
("A crime against humanity","人類に対する犯罪[No.1056]"),
("In the history of mankind","人類の歴史において[No.1057]"),
("An authority on orthodontics","歯科矯正学の権威[No.1058]"),
("Have a strong sense of justice","正義感が強い[No.1059]"),
("Have [buy] a health insurance","健康保険に入っている[No.1060]"),
("Suffer financial hardship","お金で苦労する（経済的苦難に苦しむ）[No.1061]"),
("Live below the poverty line","最低（貧困）水準以下の暮らしをする[No.1062]"),
("The kitchen is in chaos","台所がめちゃくちゃ（大混乱）だ[No.1063]"),
("In isolation from society","社会から孤立して[No.1064]"),
("A wine-producing region","ワインの生産地域[No.1065]"),
("There is no proof that she was at home at that time","彼女がその時家にいたという証拠はない[No.1066]"),
("My microwave oven was under warranty, so the repair was free","私の電子レンジは保証期間中だったので、修理は無料だった[No.1067]"),
("In principle","原則的には[No.1068]"),
("The origin of life on Earth","地球上の生命の起源[No.1069]"),
("A perfect setting for a picnic","ピクニックにはうってつけの環境[No.1070]"),
("A mission to Saturn","土星への（飛行）任務[No.1071]"),
("The outline of the new project","新企画の概要[No.1072]"),
("Put up a monument","記念碑を立てる[No.1073]"),
("A revolution in health care","医療の大改革[No.1074]"),
("Sign a contract with the team","そのチームと契約をする[No.1075]"),
("improve the tourism infrastructure","観光インフラを整備する[No.1076]"),
("Negotiate with kidnappers","誘拐犯と交渉する[No.1077]"),
("We all cooperated in preparing for the cultural festival","私たち全員で協力して文化祭の準備をした[No.1078]"),
("Restore peace in the Middle East","中東での平和を回復する[No.1079]"),
("Our school was founded in 1918","我が校は1918年に創立された[No.1080]"),
("The conservative party","保守党[No.1081]"),
("International affairs","国際情勢[No.1082]"),
("The Central Intelligence Agency (CIA)","アメリカ中央情報局[No.1083]"),
("The city council","市議会[No.1084]"),
("the animal Kingdom","動物界[No.1085]"),
("The People's Republic of China","中華人民共和国[No.1086]"),
("The fall of the Roman Empire","ローマ帝国の崩壊[No.1087]"),
("Give economic aid to developing countries","発展途上国へ経済援助を行う[No.1088]"),
("The government's educational reform","政府の教育改革[No.1089]"),
("The foreign minister","外務大臣[No.1090]"),
("summon a the parliament","議会を招集する[No.1091]"),
("the issue of the Northern Territories","北方領土問題[No.1092]"),
("Recent opinion polls","最近の世論調査[No.1093]"),
("Make a fortune in real estate","不動産で一財産を作る[No.1094]"),
("Intellectual property","知的財産[No.1095]"),
("Manage funds effectively","資金を有効に活用する[No.1096]"),
("Make money on the stock market","株（式市場）でもうける[No.1097]"),
("Manual labor","肉体労働[No.1098]"),
("Stop overworking","働きすぎをやめる[No.1099]"),
("A law firm","法律事務所[No.1100]"),
("A union member","労働組合員[No.1101]"),
("School administration","学校運営[No.1102]"),
("The Central Intelligence Agency (CIA)","アメリカ中央情報局[No.1083]"),
("The city council","市議会[No.1084]"),
("the animal Kingdom","動物界[No.1085]"),
("The People's Republic of China","中華人民共和国[No.1086]"),
("The fall of the Roman Empire","ローマ帝国の崩壊[No.1087]"),
("Give economic aid to developing countries","発展途上国へ経済援助を行う[No.1088]"),
("The government's educational reform","政府の教育改革[No.1089]"),
("The foreign minister","外務大臣[No.1090]"),
("summon a the parliament","議会を招集する[No.1091]"),
("the issue of the Northern Territories","北方領土問題[No.1092]"),
("Recent opinion polls","最近の世論調査[No.1093]"),
("Make a fortune in real estate","不動産で一財産を作る[No.1094]"),
("Intellectual property","知的財産[No.1095]"),
("Manage funds effectively","資金を有効に活用する[No.1096]"),
("Make money on the stock market","株（式市場）でもうける[No.1097]"),
("Manual labor","肉体労働[No.1098]"),
("Stop overworking","働きすぎをやめる[No.1099]"),
("A law firm","法律事務所[No.1100]"),
("A union member","労働組合員[No.1101]"),
("School administration","学校運営[No.1102]"),
("A secretary to the president.","社長秘書。[No.1103]"),
("The editor of the Japan News.","『ジャパンニュース』の編集長。[No.1104]"),
("The lawyer met a client yesterday.","その弁護士は依頼人と昨日会った。[No.1105]"),
("recruit a new band member.","新規のバンドメンバーを入れる。[No.1106]"),
("On the basis of a new theory.","新しい理論を根拠にして。[No.1107]"),
("A key element of his success.","彼の成功の鍵となる要素。[No.1108]"),
("Fifty states constitute the USA.","50の州が米国を構成している。[No.1109]"),
("Unify the country.","国を統一する。[No.1110]"),
("combine a diet with exercise.","ダイエットと運動をむすびつける。[No.1111]"),
("Unite in fighting poverty.","貧困撲滅で団結する。[No.1112]"),
("a strong link between reading and academic success.","読書と学業の成功との強い関連。[No.1113]"),
("Your arguments are not relevant to this discussion.","君の主張はこの議論と関連がない。[No.1114]"),
("a brutal murder","残忍な殺人。[No.1115]"),
("arrest a man for shoplifting","万引で男を逮捕する。[No.1116]"),
("Eric is in prison.","エリックは服役中（刑務所の中）だ。[No.1117]"),
("fight against vice on the streets","街の犯罪と戦う。[No.1118]"),
("the only witness to the murder","その殺人の唯一の目撃者。[No.1119]"),
("The bullet passed through his right leg.","弾丸は彼の右足を貫通した。[No.1120]"),
("a double-edged sword.","諸刃の剣[No.1121]"),
("The wound still hurts.","傷がまだ痛む。[No.1122]"),
("her triumph in the election","選挙での彼女の勝利。[No.1123]"),
("use military force","軍事力を使う。[No.1124]"),
("a strategy for winning the game","その試合に勝つための戦略。[No.1125]"),
("The Normans conquered England in 1066.","1066年, ノルマン人はイングランドを征服した。[No.1126]"),
("learn karate to defend myself","自分の身を守るために空手を習う。[No.1127]"),
("Donald is dominated by his wife.","ドナルドは奥さんの尻に敷かれている（奥さんに支配されている）。[No.1128]"),
("The pirates robbed the ship.","海賊はその船を襲った。[No.1129]"),
("Diana was deprived of her civil rights.","ダイアナは公民権を剥奪された。[No.1130]"),
("The city was devastated by a big earthquake.","その都市は大地震で壊滅した。[No.1131]"),
("crash into the barrier.","ガードレールに激突する。[No.1132]"),
("Steep stairs can be a hazard for elderly people.","急な階段は高齢者にとって危険になり得る。[No.1133]"),
("clear space debris","宇宙ゴミを片付ける。[No.1134]"),
("a war orphan","戦争孤児。[No.1135]"),
("free the slaves","奴隷を解放する。[No.1136]"),
("an old acquaintance","昔からの知り合い。[No.1137]"),
("a wine merchant","ワイン店を営む人。[No.1138]"),
("Parking spaces are for residents only.","駐車スペースは居住者専用です。[No.1139]"),
("passengers and crew on the plane.","飛行機の乗客と乗組員。[No.1140]"),
("Police chased the stolen car.","警察はその盗難車を追いかけた。[No.1141]"),
("First, please proceed to Gate 3.","まず、3番ゲートへお進みください。[No.1142]"),
("Childhood memories fade as time passes.","時が過ぎるとともに子どものころの記憶は薄れる。[No.1143]"),
("Salt dissolves in hot water.","塩が熱湯に溶ける。[No.1144]"),
("float on the sea","海面に浮かぶ。[No.1145]"),
("Oil does not sink in water.","油は水に沈まない。[No.1146]"),
("The ball bounced over the wall.","ボールは跳ねて壁を超えた。[No.1147]"),
("transform the old house into a restaurant","古い家を改造してレストランにする。[No.1148]"),
("a paradigm shift","パラダイムシフト（理論的枠組の転換）。[No.1149]"),
("genetically modified (GM) foods","遺伝子組み換え食品。[No.1150]"),
("revise the educational system","教育制度を改正する。[No.1151]"),
("enhance my aesthetic sense","美意識を磨く（向上させる）。[No.1152]"),
("lower the voting age from 20 to 18.","選挙権年齢を20歳から18歳に引き下げる。[No.1153]"),
("take a voyage around the world","世界一周の船旅をする。[No.1154]"),
("confirm the booking","予約を確認する。[No.1155]"),
("Please ensure that you leave nothing behind.","忘れ物をしないように気をつけてください。[No.1156]"),
("address an environmental problem","環境問題に取り組む。[No.1157]"),
("a new approach to teaching languages","言語教育への新たな取り組み方。[No.1158]"),
("resolve the matter on my own","自分でその問題を解決する。[No.1159]"),
("settle the dispute","その紛争を解決する。[No.1160]"),
("enrich the soil","その土壌を豊かにする。[No.1161]"),
("warn him to follow the rules","規則に従うよう彼に警告する。[No.1162]"),
("The older kids forced him to shoplift.","年上の子達が彼に万引するよう強いた。[No.1163]"),
("appeal to our emotions","私たちの感情に訴えかける。[No.1164]"),
("receive hearty applause","心からの拍手をもらう。[No.1165]"),
("A fish leaped out of a pond.","魚が池の中から跳び出た。[No.1166]"),
("grab him by the neck","彼の首根っこをつかむ。[No.1167]"),
("seize her by the shoulder","彼女の肩をつかむ。[No.1168]"),
("cast a net around a school of tuna.","マグロの群れに網を投げ入れる。[No.1169]"),
("stun him with a blow.","殴って彼を気絶させる。[No.1170]"),
("a beautifully illuminated castle.","美しく照らされた城。[No.1171]"),
("uncover a scandal.","不祥事を暴く。[No.1172]"),
("mend a tear in my jacket.","上着のほころびを修繕する。[No.1173]"),
("react angrily to the news.","その知らせに怒りの反応を示す。[No.1174]"),
("endure years of suffering.","長年の苦労に耐える。[No.1175]"),
("bind two communities together.","2つの会社を結びつける。[No.1176]"),
("encounter a bear in the woods.","森の中でクマに遭遇する。[No.1177]"),
("trace a missing person.","行方不明の人を捜し出す。[No.1178]"),
("undergo cosmetic surgery.","美容整形手術を受ける。[No.1179]"),
("a sealed container.","密閉容器。[No.1180]"),
("Many words have been incorporated into English from Latin.","多くの単語がラテン語から英語に取り入れられた。[No.1181]"),
("emerge from the darkness.","暗闇から現れる。[No.1182]"),
("How will that drama unfold?","そのドラマはどのように展開するのだろう。[No.1183]"),
("This word derives from Latin.","この単語はラテン語に由来する。[No.1184]"),
("generate electricity.","電気を生み出す。[No.1185]"),
("Every child possesses a range of abilities.","どの子も多彩な才能を所有している。[No.1186]"),
("retain her beauty.","彼女の美しさを保持する。[No.1187]"),
("secure a window seat.","窓側の席を確保する。[No.1188]"),
("The monkey that escaped from the zoo was captured.","動物園から逃げたサルが確保された。[No.1189]"),
("monitor my blood pressure.","血圧をチェックする。[No.1190]"),
("investigate the ecology of eels.","ウナギの生態を調査する。[No.1191]"),
("detect a small amount of drug.","微量の麻薬を検出する。[No.1192]"),
("an inquiry into his background.","彼の身元調査。[No.1193]"),
("specialize in business administration.","経営学を専攻する。[No.1194]"),
("the first semester.","前期。[No.1195]"),
("Biology is the scientific study of living things.","生物学は生物の科学的な研究です。[No.1196]"),
("the ecology of jellyfish.","クラゲの生態。[No.1197]"),
("the philosophy of Aristotle.","アリストテレスの哲学。[No.1198]"),
("a great discovery in geography.","地理上の偉大な発見。[No.1199]"),
("educational institutions.","教育機関。[No.1200]"),
("the faculty of hearing.","聴力。[No.1201]"),
("an intermediate course.","中級の講座。[No.1202]"),
("the notion that smoking is cool.","タバコを吸うのは格好いいという考え。[No.1203]"),
("the concept of time.","時間の概念。[No.1204]"),
("sit in Zen meditation.","座禅を組む。[No.1205]"),
("an insight into human nature.","人間性への洞察。[No.1206]"),
("act with caution.","用心して行動する。[No.1207]"),
("against my will.","意思に反して。[No.1208]"),
("consider other options.","ほかの選択肢を考える。[No.1209]"),
("I was both excited and worried at the prospect of becoming a father.","自分が父親になることを考えるとワクワクすると同時に不安だった。[No.1210]"),
("cherish the memories of that day.","その日の思い出を大切にする。[No.1211]"),
("intend to see the movie.","その映画を見るつもりだ。[No.1212]"),
("The police suspect that she stole the money.","警察は彼女がそのお金を盗んだのではないかと思っている。[No.1213]"),
("identify the fingerprints.","その指紋を特定する。[No.1214]"),
("Parking is not permitted here.","ここでは駐車は許可されていません。[No.1215]"),
("acknowledge the need for change.","変化の必要性を認める。[No.1216]"),
("perceive the discovery as a major breakthrough.","その発見を飛躍的進歩と認識する。[No.1217]"),
("evaluate the employees' performances.","従業員の仕事ぶりを評価する。[No.1218]"),
("cultivate the land.","土地を耕す。[No.1219]"),
("sit in the shade.","日陰に座る。[No.1220]"),
("feel a sea breeze.","海のそよ風を感じる。[No.1221]"),
("the Sahara desert.","サハラ砂漠。[No.1222]"),
("the dense fog cleared.","濃い霧が晴れた。[No.1223]"),
("Moisture is essential for keeping your skin youthful.","湿り気は皮膚を若々しく保つのに不可欠だ。[No.1224]"),
("My shirt is still damp.","シャツがまだ湿っている。[No.1225]"),
("follow a path to the mountaintop.","山頂への道をたどる。[No.1226]"),
("a hiking trail.","ハイキングコース。[No.1227]"),
("a mountain stream.","谷川。[No.1228]"),
("the tide is in.","満潮である。[No.1229]"),
("coral reef.","サンゴ礁。[No.1230]"),
("the natural habitat of sea lions.","アシカの自然生息地。[No.1231]"),
("that volcano erupted last year.","その火山は昨年噴火した。[No.1232]"),
("work in a coal mine.","炭鉱で働く。[No.1233]"),
("One swallow does not make a summer.","早合点は禁物。[No.1234]"),
("weave a web.","（クモが）巣を張る。[No.1235]"),
("I was bitten by a mosquito.","蚊に刺された。[No.1236]"),
("cattle, sheep, and other domestic animals.","ウシ、ヒツジ、とそれ以外の家畜。[No.1237]"),
("a lost kitten.","迷子の子ネコ。[No.1238]"),
("microscopic organisms.","微生物。[No.1239]"),
("the wildlife of the Galapagos Islands.","ガラパゴス諸島の野生生物。[No.1240]"),
("the lion, the king of beasts.","百獣の王ライオン。[No.1241]"),
("great apes.","大型類人猿。[No.1242]"),
("a flock of crows.","カラスの一群。[No.1243]"),
("inject a medicine into a vein.","静脈に薬を注射する。[No.1244]"),
("Rabbits breed all year round.","ウサギは年中繁殖する。[No.1245]"),
("The virus can reproduce rapidly.","ウイルスは急速に繁殖する。[No.1246]"),
("a talkative taxi driver.","おしゃべりなタクシー運転手。[No.1247]"),
("make an earnest effort.","真面目に努力する。[No.1248]"),
("a diligent student.","勤勉な学生。[No.1249]"),
("the country's principal export.","その国の主な輸出品。[No.1250]"),
("the prime minister of Japan.","日本の首相。[No.1251]"),
("a definite answer.","明確な答え。[No.1252]"),
("It was evident that he was not telling the truth.","彼が真実を言っていないのは明らかだった。[No.1253]"),
("The statue stood in a prominent position.","その像は目立った場所にあった。[No.1254]"),
("a marked change in his behavior.","彼の行動の際立った変化。[No.1255]"),
("the grace of the dancer.","そのダンサーの優美さ。[No.1256]"),
("have enormous charm.","大きな魅力がある。[No.1257]"),
("a fancy French restaurant.","高級なフレンチレストラン。[No.1258]"),
("make a rational decision.","理性的な決定をする。[No.1259]"),
("a magnificent view of Mt. Fuji.","富士山の壮大な眺め。[No.1260]"),
("Your bike is superior to mine.","君の自転車は私のより優れている。[No.1261]"),
("a loyal supporter of the team.","そのチームの忠実な支持者。[No.1262]"),
("That fish looks horrible but tastes terrific.","その魚は見た目はひどいが味はすばらしい。[No.1263]"),
("lead a miserable life.","悲惨な生活を送る。[No.1264]"),
("a dull TV program.","退屈なテレビ番組。[No.1265]"),
("leave a nasty taste in my mouth.","後味が悪い。[No.1266]"),
("Have you gone insane?","正気を失ったか。[No.1267]"),
("I believe that lowering the voting age is a ridiculous idea.","選挙年齢を引き下げるのは馬鹿げた考えだと思う。[No.1268]"),
("rotten eggs,","腐った卵。[No.1269]"),
("That clothing shop is notorious for its poor quality.","その服屋は低品質で悪名高い。[No.1270]"),
("an evil spirit.","悪霊。[No.1271]"),
("make a mess of the room.","部屋をめちゃくちゃにする。[No.1272]"),
("a vast palace.","広大な宮殿。[No.1273]"),
("a huge elephant.","巨大なゾウ。[No.1274]"),
("a tiny hole in the wall.","壁に開いたとても小さな穴。[No.1275]"),
("a perfect sphere.","完全な球体。[No.1276]"),
("a strip of paper.","細長い紙片。[No.1277]"),
("a blood vessel in the brain.","脳内の血管。[No.1278]"),
("internal organs.","内蔵。[No.1279]"),
("a mobile society.","流動的な社会。[No.1280]"),
("climb steep stone steps.","急な石段を上る。[No.1281]"),
("intense pressure to succeed.","成功しなければという強烈な重圧。[No.1282]"),
("an inevitable result.","避けられない結果。[No.1283]"),
("a demilitarized neutral zone.","非武装中立地帯。[No.1284]"),
("have a brief conversation with her.","彼女と少し話をする。[No.1285]"),
("Her arms were bare.","彼女の腕はむき出しだった。[No.1286]"),
("promote mutual understanding.","相互の理解を促進させる。[No.1287]"),
("a potential customer.","将来の顧客。[No.1288]"),
("a tough soldier.","たくましい兵士。[No.1289]"),
("conventional weapons.","通常兵器。[No.1290]"),
("the Supreme Court.","最高裁判所。[No.1291]"),
("Peter resembles his father in every way.","ピーターはあらゆる点で父親に似ている。[No.1292]"),
("Roger is not stupid; on the contrary, he is a genius.","ロジャーはバカではない。それどころか天才だ。[No.1293]"),
("fall into the same category.","同じ範疇に属する。[No.1294]"),
("limit the scope of our activities.","私たちの活動範囲を制限する。[No.1295]"),
("a given period of time.","ある一定の期間。[No.1296]"),
("a custom peculiar to Japan.","日本固有の習慣。[No.1297]"),
("sufficient food for everyone.","全員に行き渡る十分な食料。[No.1298]"),
("on numerous occasions.","多くの場面で。[No.1299]"),
("a substantial breakfast.","ボリュームのある朝食。[No.1300]"),
("The family is the smallest unit of society.","家族は社会の最小の単位だ。[No.1301]"),
("two meters in diameter.","直径2メートル。[No.1302]"),
("reading, writing and arithmetic.","読み、書き、算盤。[No.1303]"),
("Quality is more important than quantity.","量より質が重要だ。[No.1304]"),
("a vitamin deficiency.","ビタミンの欠乏。[No.1305]"),
("This will cost a maximum of 1000 dollars.","これは最大で1,000ドルかかります。[No.1306]"),
("a bunch of flowers.","花束。[No.1307]"),
("lessen the risk of human error.","人為的ミスのリスクを軽減する。[No.1308]"),
("the dawn of a new era.","新たな時代の幕開け。[No.1309]"),
("have a Q&A session.","質疑応答の時間をとる。[No.1310]"),
("begin to speak after a long pause.","長い休止の後に話し始める。[No.1311]"),
("the annual report.","年次報告書。[No.1312]"),
("Do you believe in eternal life?","永遠の命を信じますか。[No.1313]"),
("the initial stages of the disease","その病気の初期段階。[No.1314]"),
("prior to the meeting","会議の前に。[No.1315]"),
("subsequent events","続いて起こった出来事。[No.1316]"),
("My wife was shopping. Meanwhile, I was waiting in the car.","妻は買い物をしていた。その間私は車で待っていた。[No.1317]"),
("Sweeping the street in front of my house is part of my daily routine.","家の前の道路を掃くことは日課の一部です。[No.1318]"),
("a souvenir of my trip to France.","フランス旅行の記念品。[No.1319]"),
("a brick house.","れんが造りの家。[No.1320]"),
("a ten-foot bamboo pole.","10フィートの竹ざお。[No.1321]"),
("a child who loves mischief.","いたずらが好きな子ども。[No.1322]"),
("the superstition that rooms numbered 4 are unlucky.","4号室は不吉であるという迷信。[No.1323]"),
("I need more storage space.","もっと多くの貯蔵スペースが必要だ。[No.1324]"),
("take shelter from the rain.","雨宿りする。[No.1325]"),
("Delicate garments should be handwashed.","傷みやすい衣類は手洗いしなければならない。[No.1326]"),
("the Suez Canal.","スエズ運河。[No.1327]"),
("put the forms in the filing cabinet.","書類整理棚にその書類をしまう。[No.1328]"),
("The incident occurred at around 3 a.m.","その出来事は午前3時ごろに起きた。[No.1329]"),
("The circumstances are changing minute by minute.","状況は刻一刻と変化している。[No.1330]"),
("fetch the children from the kindergarten.","幼稚園に子どものお迎えに行く。[No.1331]"),
("distribute handouts.","プリントを配る。[No.1332]"),


       ]

import streamlit as st
from docx import Document
import io
# PDFを作るためのライブラリ
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.units import mm

# --- 🔐 パスワード認証機能 ---
# ここで「金庫の中のパスワード」と「入力されたパスワード」を照合します
password = st.text_input("パスワードを入力してください", type="password")
if password != st.secrets["MY_PASSWORD"]:
    st.warning("正しいパスワードを入力するとアプリが使えます。")
    st.stop()  # ここで処理を強制ストップ（これより下のコードは動きません）


# --- 2. 画面の設定 ---
st.title("単語・例文テスト作成アプリ 📝")
st.write("範囲と問題数を指定してください。PDFで出力します。")

# 入力欄
col1, col2, col3 = st.columns(3)
with col1:
    s = st.number_input('開始番号 (No.)', min_value=1, value=1)
with col2:
    f = st.number_input('終了番号 (No.)', min_value=1, value=len(leap1))
with col3:
    q_num = st.number_input('出題数', min_value=1, value=20)

# --- 3. PDFを作成する関数 ---
def create_pdf(questions, answers, start_num, end_num, actual_num):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    
    # ★フォントの登録
    try:
        pdfmetrics.registerFont(TTFont('Japanese', 'ipaexg.ttf'))
        font_name = 'Japanese'
    except:
        st.error("エラー：'ipaexg.ttf' が見つかりません。GitHubにアップロードしましたか？")
        font_name = 'Helvetica'

    width, height = A4
    c.setFont(font_name, 10.5) # フォントサイズ
    
    # --- タイトルの描画（Wordに合わせる）---
    # 1行目：名前と範囲
    title_text = f"名前:＿＿＿＿＿＿＿＿＿＿＿＿＿＿   範囲：No.{start_num}～{end_num} からランダムに{actual_num}問"
    c.drawString(20*mm, height - 20*mm, title_text)
    
    # 2行目：注釈
    c.drawString(20*mm, height - 28*mm, "答えの〔No.～〕は単語番号です。")
    
    # 描画開始位置
    y_position = height - 45*mm
    
    for i in range(len(questions)):
        # 改ページ処理
        if y_position < 20*mm:
            c.showPage()
            c.setFont(font_name, 10.5)
            y_position = height - 20*mm

        q_text = questions[i]
        
        # 問題文（Qを削除して、番号: 全角スペース 問題文）
        c.drawString(20*mm, y_position, f"{i+1}:　{q_text}")
        
        # 下線（問題文の下に引く）
        c.drawString(20*mm, y_position - 8*mm, "＿＿" * 25) 
        
        # 次の問題へ（間隔を調整）
        y_position -= 20*mm

    c.save()
    return buffer.getvalue()

# 解答用PDF
def create_answer_pdf(questions, answers, start_num, end_num, actual_num):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    
    try:
        pdfmetrics.registerFont(TTFont('Japanese', 'ipaexg.ttf'))
        font_name = 'Japanese'
    except:
        font_name = 'Helvetica'

    width, height = A4
    c.setFont(font_name, 10.5)
    
    # タイトル
    title_text = f"名前:＿＿＿＿＿＿＿＿＿＿＿＿＿＿   範囲：No.{start_num}～{end_num} からランダムに{actual_num}問"
    c.drawString(20*mm, height - 20*mm, title_text)
    c.drawString(20*mm, height - 28*mm, "答えの〔No.～〕は単語番号です。")
    
    y_position = height - 45*mm
    
    for i in range(len(questions)):
        if y_position < 20*mm:
            c.showPage()
            c.setFont(font_name, 10.5)
            y_position = height - 20*mm

        q_text = questions[i]
        a_text = answers[i]
        
        # 問題文
        c.drawString(20*mm, y_position, f"{i+1}:　{q_text}")
        # 答え
        c.drawString(20*mm, y_position - 8*mm, f"      {a_text}")
        
        y_position -= 20*mm

    c.save()
    return buffer.getvalue()


# --- 4. 作成処理 ---
if st.button('PDFテストを作成する！'):
    
    if s > f:
        st.error("範囲エラー：開始番号が終了番号より大きいです。")
        st.stop()
    
    target_data = leap1[s-1 : f]
    if len(target_data) < 1:
        st.error("データなし：指定された範囲にデータがありません。")
        st.stop()

    actual_q_num = min(q_num, len(target_data))
    random.shuffle(target_data)
    selected_data = target_data[:actual_q_num]
    
    test_dict = dict(selected_data)
    questions = list(test_dict.keys())
    answers = list(test_dict.values())
    
    # PDFを作成（関数に引数を渡す）
    pdf_q = create_pdf(questions, answers, s, f, actual_q_num)
    pdf_a = create_answer_pdf(questions, answers, s, f, actual_q_num)
    
    # セッションステートに保存
    st.session_state['pdf_q'] = pdf_q
    st.session_state['pdf_a'] = pdf_a
    st.session_state['suffix'] = f"{s}～{f}"
    
    st.success(f"PDF作成完了！({actual_q_num}問)")

# --- 5. ダウンロード ---
if 'pdf_q' in st.session_state:
    st.write("---")
    col1, col2 = st.columns(2)
    suffix = st.session_state['suffix']
    
    with col1:
        st.download_button(
            label="📄 問題PDFをDL",
            data=st.session_state['pdf_q'],
            file_name=f"LEAP_テスト{suffix}.pdf",
            mime="application/pdf"
        )
    with col2:
        st.download_button(
            label="📄 答えPDFをDL",
            data=st.session_state['pdf_a'],
            file_name=f"LEAP_答え{suffix}.pdf",
            mime="application/pdf"

        )
